// Script Doctor — calibration reference corpus (Deliverable 1 of the
// calibration feature; the distribution built from these samples lives in
// ./reference.ts, the percentile math in ./percentile.ts).
//
// ── What this is ──────────────────────────────────────────────────────────
// 20 ORIGINAL, hand-authored sample Fountain screenplays, deliberately
// spanning four quality bands (5 each): 'strong', 'competent', 'weak',
// 'troubled'. None of this is copied from — or based on — any real,
// produced, or copyrighted screenplay; every premise, character, and line of
// dialogue below was written for this corpus. This is a small, curated
// reference SET for relative calibration ("stronger than 74% of the
// reference set"), not a claim about "all produced screenplays" — see
// reference.ts's and percentile.ts's header comments for the honesty
// requirement this satisfies.
//
// ── CONTROLLED-RICHNESS DESIGN (read this before editing a sample) ────────
// Earlier corpus revisions varied wildly in scene count (8-12) and word
// count (~200-520) BY BAND — 'strong' samples were the longest and richest,
// 'troubled' samples the shortest and barest. That confounded the experiment:
// the ~1,300-rule pipeline's structural-absence and prose-texture checks
// scale with scene count and word count more than with authored quality, so
// a richer mid-quality script could out-penalize a barren troubled one on
// the raw craft score, even though the raw formula (doctor.ts's
// craftPenalty) already normalizes by scene count. Averaged per band, that
// defect made 'competent' rank LOWEST of all four bands and let one strong
// sample rank below every troubled sample — see reference.ts's former KNOWN
// LIMITATION block (now superseded).
//
// The fix here is experimental-design, not score-gaming: every sample below
// is now built from the SAME 10-scene skeleton with a tightly matched word
// budget (~300-360 words), so RICHNESS is held constant across all four
// bands and CRAFT is the only independent variable left to vary. Every
// sample — troubled included — carries dialogue, action, at least one
// clock/deadline mention, at least one planted setup (a quoted clue phrase),
// and a two-character relationship beat (an old grievance surfacing). Bands
// differ ONLY in how well those elements are executed:
//   'strong'    — clue paid off late (scene 9 of 10, ~90%, well past the
//                 midpoint), a genuine revelation past the midpoint (scene
//                 6), the clock mentioned in both halves and honored,
//                 escalating danger/urgency language into the climax, and a
//                 full relationship arc: rupture (scene 4) resolved with a
//                 distinct, earned Act 3 reconciliation (scene 10).
//   'competent' — the identical skeleton with real, deliberate flaws: the
//                 clue pays off early (scene 6, ~60%) instead of at the
//                 climax, so scene 9 has nothing left to resolve; two scenes
//                 (5 and 7) share the same low-momentum "nothing new" beat
//                 (flat midsection); one stock/cliche reassurance line
//                 appears; and the Act 3 relationship beat is a thin,
//                 shorter acknowledgment rather than a full reconciliation.
//                 Recognizably good-faith craft, not a first draft.
//   'weak'      — the clock is stated once and never followed up on; the
//                 clue eventually gets addressed but flatly, procedurally,
//                 with no reversal and no danger/urgency language anywhere;
//                 two scenes (5 and 6) repeat the same beat almost verbatim;
//                 the relationship rupture gets NO resolution — the two
//                 characters simply part on a non-committal line; a
//                 stock/cliche phrase appears in the closing scenes.
//   'troubled'  — pervasive failures at the SAME richness, not barrenness:
//                 the clock is stated once and then flatly contradicted (the
//                 deadline passes with zero narrative consequence); the clue
//                 is seeded and genuinely orphaned (never mentioned again,
//                 so it is a true single-occurrence unresolved clue, not a
//                 "gap too small" near-miss); there is no revelation at all;
//                 four consecutive scenes (5-8) recycle the identical
//                 "same as always" purpose and near-identical phrasing; the
//                 relationship beat gets zero movement — both voices stay
//                 interchangeable start to finish; and the dialogue leans
//                 hard on the on-the-nose/cliche lexicon dialogue.ts and
//                 originality.ts already flag ("I feel so X, honestly",
//                 "Trust me on this", "Everything's fine", "Same as always").
//
// ── Constraint for future corpus editors (do not silently violate) ────────
// When adding, replacing, or rebalancing a sample: keep it at 10 scenes
// (skeleton positions above) and within the ~300-360 word band every other
// sample uses. Vary premise, character names, and EXECUTED CRAFT freely —
// never vary richness (scene count, word count, or which structural signals
// are present) to make a band look better or worse. A sample that is barren
// (missing the clock, the clue, or the relationship beat) is not a
// legitimate 'troubled' sample under this design — it reintroduces the exact
// richness confound this rebalance exists to remove. tests/core/
// calibration.test.ts enforces the band-average ordering this design
// produces; a corpus edit that breaks that ordering is a signal the edit
// violated the richness constraint, not that the test needs loosening.
//
// Every sample is exactly 10 scenes so the per-scene structural signals
// above have identical room to register in every band.

export type CorpusBand = 'strong' | 'competent' | 'weak' | 'troubled';

export interface CorpusSample {
  label: string;
  band: CorpusBand;
  fountain: string;
}

// ── STRONG (5) ───────────────────────────────────────────────────────────

const LOW_TIDE = [
  'INT. HARBOR NEWSROOM - NIGHT',
  '',
  'Whit stares at a dead newsroom phone, the building emptying for the night.',
  '',
  'WHIT',
  "Nobody's checked the docks since the trawler went quiet.",
  '',
  'EXT. FISH DOCKS - DAWN',
  '',
  'Reyes checks the tide chart taped to her dash, counting hours.',
  '',
  'REYES',
  'The tide erases every footprint out there by nine.',
  '',
  'INT. TRAWLER CABIN - DAY',
  '',
  'Whit pries a torn ledger page from under the wheel.',
  '',
  'WHIT',
  '"The manifest never left the harbor." Someone wanted that found.',
  '',
  'REYES',
  'Found by us, or by whoever wrote it?',
  '',
  'INT. REYES CAR - NIGHT',
  '',
  "Reyes admits she knew Whit's brother worked that boat.",
  '',
  'WHIT',
  'You knew and said nothing to me for months.',
  '',
  'REYES',
  "I was protecting you. You're angry at me for it.",
  '',
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  'They pin the ledger photo beside a manifest with mismatched numbers.',
  '',
  'REYES',
  'Two sets of figures for one cargo load.',
  '',
  'EXT. CANNERY LOADING DOCK - DUSK',
  '',
  'Behind a loose brick, Reyes finds a second logbook stamped by the harbor master.',
  '',
  'REYES',
  "He signed every falsified page. That's a confession.",
  '',
  'WHIT',
  'So the harbor master built the second boat, not my brother.',
  '',
  'EXT. CONTAINER YARD - NIGHT',
  '',
  'A forklift roars as a floodlight sweeps the containers, hours from sailing.',
  '',
  'REYES',
  'If that container clears the breakwater, we lose the case.',
  '',
  'EXT. CONTAINER YARD - CONTINUOUS',
  '',
  'A foreman blocks the gate, shouting over the crane.',
  '',
  'FOREMAN',
  "You're too late, it's already sealed.",
  '',
  'EXT. CONTAINER YARD - MOMENTS LATER',
  '',
  'Whit finds the matching torn page taped inside the container door.',
  '',
  'WHIT',
  'The manifest never left the harbor. It was rerouted.',
  '',
  'REYES',
  'They needed everyone watching the water, not the yard.',
  '',
  'EXT. REYES HOUSE - PORCH - MORNING',
  '',
  'Whit and Reyes sit on the porch as the harbor calms behind them.',
  '',
  'WHIT',
  "I'm grateful you never stopped looking, even angry.",
  '',
  'REYES',
  'We forgive each other and start over.',
].join('\n');

const NINE_MINUTES = [
  'INT. NEGOTIATION VAN - NIGHT',
  '',
  'Priya studies a bank floor plan while Sam pours two untouched coffees.',
  '',
  'PRIYA',
  'Four hostages, one shooter, a manager who thinks he can talk his way out.',
  '',
  'INT. BANK LOBBY - NIGHT',
  '',
  'Marcus paces near the vault, nine minutes left before the deadline.',
  '',
  'MARCUS',
  'Nine minutes. Somebody better start believing me.',
  '',
  'INT. NEGOTIATION VAN - CONTINUOUS',
  '',
  "Sam hands Priya a folder from the shooter's own file.",
  '',
  'SAM',
  '"He needs cash for a transplant he can\'t get approved." His daughter\'s file.',
  '',
  'PRIYA',
  "Then that's where we start.",
  '',
  'INT. NEGOTIATION VAN - CONTINUOUS',
  '',
  'Sam and Priya argue in a hushed whisper, an old wound surfacing again.',
  '',
  'SAM',
  "You promised after the courthouse job you'd stop walking in without backup.",
  '',
  'PRIYA',
  "And you promised you'd trust my read on a room. Pick one.",
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  'Priya talks Marcus down a notch as one hostage faints near the vault.',
  '',
  'PRIYA',
  "Marcus, I know about your daughter. Let's find a way that isn't a cell.",
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  'Marcus is stalling: a second guard waits at the side exit.',
  '',
  'MARCUS',
  'It was never just me. My brother-in-law set this up months ago.',
  '',
  'INT. BANK VESTIBULE - CONTINUOUS',
  '',
  'Alarms blare and glass shatters, two minutes left on the countdown.',
  '',
  'SAM',
  "Two minutes. If she's not talking him down, command takes the door.",
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  'Marcus grabs a hostage and drags her toward the side door.',
  '',
  'MARCUS',
  "Nobody move! I swear I'll do it!",
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  "",
  "The gun clatters down the instant Priya's voice comes through the speaker.",
  '',
  'PRIYA (V.O.)',
  'Marcus, put it down. Your daughter needs her father, not a headline.',
  '',
  'MARCUS',
  "Okay. Just get her the surgery. That's all I ever wanted.",
  '',
  'INT. HOSPITAL CORRIDOR - MORNING',
  '',
  'Priya and Sam sit together, quiet at last. Sam takes her hand.',
  '',
  'SAM',
  "I'm grateful you were right about the room. I should have trusted you sooner.",
  '',
  'PRIYA',
  "We forgive the mistakes. That's never the hard part.",
].join('\n');

const THE_LONG_GAME = [
  'INT. WAREHOUSE HIDEOUT - NIGHT',
  '',
  'Odell lays blueprints across a table, each corner weighted down with a coin.',
  '',
  'ODELL',
  'Three exits, two guards, one blind spot for four seconds.',
  '',
  'EXT. MUSEUM STREET - DUSK',
  '',
  'Cass clocks the guard rotation from a parked car.',
  '',
  'CASS',
  "Sunrise, Odell. That's the whole window.",
  '',
  'INT. RECORDS OFFICE - NIGHT',
  '',
  'Odell photographs a duty sheet, quiet and precise, before the office reopens.',
  '',
  'ODELL',
  '"The vault opens at three." Somebody wrote the exact minute down for us.',
  '',
  'INT. HIDEOUT KITCHEN - NIGHT',
  '',
  'Cass and Odell argue over an old betrayal neither has said aloud in years.',
  '',
  'CASS',
  "You left me holding the last job alone and never once said sorry.",
  '',
  'ODELL',
  "I was protecting the crew, and you resent me for keeping you out of prison.",
  '',
  'INT. HIDEOUT - NIGHT',
  '',
  'The crew rehearses the route on a chalk floor plan, timing each other.',
  '',
  'ODELL',
  'Ninety seconds in the east corridor, or the second guard clears the corner.',
  '',
  'INT. MUSEUM SERVER ROOM - NIGHT',
  '',
  "Odell finds the buyer's name on an internal memo: Cass fed the schedule from the start.",
  '',
  'ODELL',
  'I knew it. Somebody on this crew has been talking.',
  '',
  'CASS',
  "Say it to my face, Odell, or don't say it at all.",
  '',
  'EXT. MUSEUM STREET - PRE-DAWN',
  '',
  'A rival crew arrives early, guns drawn, the alley loud with shouting.',
  '',
  'RIVAL LEADER',
  'Nobody touches that vault but us! Move!',
  '',
  'INT. MUSEUM VAULT CORRIDOR - CONTINUOUS',
  '',
  'Gunfire echoes down the corridor as Odell and Cass sprint for the ninety-second window.',
  '',
  'CASS',
  'Go, go, now!',
  '',
  'INT. MUSEUM VAULT - CONTINUOUS',
  '',
  'The vault door eases open exactly at three, just as the note promised all along.',
  '',
  'ODELL',
  'It opens at three. Exactly like it said.',
  '',
  'EXT. SAFEHOUSE ROOFTOP - SUNRISE',
  '',
  'Cass and Odell watch the sun rise over the city, calm at last. Cass offers a hand.',
  '',
  'CASS',
  "I'm grateful you came back for me in that corridor. I forgive the rest.",
  '',
  'ODELL',
  'We trust each other again, starting now. That was always the long game.',
].join('\n');

const SECOND_WIND = [
  'INT. GYM - MORNING',
  '',
  'Theo wraps his own hands, slow and careful, the gym empty this early.',
  '',
  'THEO',
  "Nobody thinks a thirty-nine-year-old gets a second title shot.",
  '',
  'EXT. BOARDWALK - DAWN',
  '',
  'Theo runs the pier at dawn; six weeks are left before the fight.',
  '',
  'RUTH',
  'Six weeks. We build the legs first, the chin later.',
  '',
  'INT. GYM OFFICE - DAY',
  '',
  "Ruth finds an old note tucked in Theo's locker and reads it aloud.",
  '',
  'RUTH',
  '"Never good enough for him." Your father wrote that on your first fight poster.',
  '',
  'INT. THEO APARTMENT - NIGHT',
  '',
  'Ruth pushes too hard on an old wound and Theo pushes back.',
  '',
  'THEO',
  "You don't get to bring up my father like you knew him.",
  '',
  'RUTH',
  "I'm not backing off, Theo, and you resent me for pushing anyway.",
  '',
  'INT. GYM - DAY',
  '',
  "Theo works the heavy bag at camp's midpoint, form finally sharpening.",
  '',
  'RUTH',
  'That combination right there. That is the fight, Theo.',
  '',
  'INT. GYM - NIGHT',
  '',
  "Ruth learns the truth: Theo's father kept every clipping, hidden, never shown.",
  '',
  'RUTH',
  'Turns out he kept every article about you. He was proud.',
  '',
  'THEO',
  'I always hoped there was something, and nobody ever told me.',
  '',
  'EXT. TRAINING CAMP - DAY',
  '',
  "A rival fighter's camera crew rattles Theo two weeks before the bout.",
  '',
  'RIVAL FIGHTER',
  "Two weeks, old man. Enjoy the attention while it lasts.",
  '',
  'INT. ARENA - LOCKER ROOM - NIGHT',
  '',
  "Theo's nerve cracks just before the final bell of camp.",
  '',
  'THEO',
  "I don't know if I can carry both fights at once.",
  '',
  'INT. ARENA - RING - NIGHT',
  '',
  "Theo lands the combination Ruth drilled at the midpoint, the crowd erupting.",
  '',
  'ANNOUNCER',
  'And the new champion!',
  '',
  'INT. ARENA - CORRIDOR - NIGHT',
  '',
  'Theo and Ruth stand together, calm and quiet after the roar of the crowd.',
  '',
  'THEO',
  "I'm grateful you never let me hide from any of it.",
  '',
  'RUTH',
  "We forgive the years we lost. I trust there's plenty more ahead.",
].join('\n');

const SUNLIGHT_CLAUSE = [
  'INT. CHEMPLANT OFFICE - DAY',
  '',
  'Dana copies a stack of internal memos after hours, the building quiet.',
  '',
  'DANA',
  "Nobody outside this building knows what's in the runoff numbers.",
  '',
  'INT. LAW OFFICE - DAY',
  '',
  'Ben reviews a filing calendar; the injunction deadline is one week away.',
  '',
  'BEN',
  "One week. Miss the filing and the plant runs through summer unchecked.",
  '',
  'INT. DANA APARTMENT - NIGHT',
  '',
  'Dana finds a memo buried on purpose in an old email thread.',
  '',
  'DANA',
  '"The sunlight clause expires at midnight Friday." Someone buried this on purpose.',
  '',
  'INT. LAW OFFICE - NIGHT',
  '',
  'Ben confronts Dana over the risk she took entirely alone.',
  '',
  'BEN',
  "You could lose your job and you didn't think to warn me first.",
  '',
  'DANA',
  "I was afraid, and I resent that you might've been right.",
  '',
  'INT. LAW OFFICE - DAY',
  '',
  'Ben and Dana build the case at the midpoint, cross-referencing memos.',
  '',
  'BEN',
  'This paragraph right here. This is the whole case if we can prove intent.',
  '',
  'INT. CHEMPLANT EXECUTIVE OFFICE - NIGHT',
  '',
  'Ben finds a signed authorization proving the executive knew about the runoff for a year.',
  '',
  'BEN',
  'Turns out they knew in March. Every month since was a choice, not an accident.',
  '',
  'DANA',
  "I hoped I was wrong, and I wasn't.",
  '',
  'EXT. CHEMPLANT PARKING LOT - NIGHT',
  '',
  'A company lawyer intercepts Dana as midnight Friday closes in.',
  '',
  'COMPANY LAWYER',
  "You testify, we bury you in litigation for a decade.",
  '',
  'INT. COURTHOUSE STEPS - MORNING',
  '',
  "Midnight has come and gone; reporters shout questions before the clerk's window closes.",
  '',
  'REPORTER',
  "Dana, is it true the clause expired last night?",
  '',
  'INT. COURTHOUSE CLERK WINDOW - CONTINUOUS',
  '',
  'Ben slides the filing across the counter with seconds to spare.',
  '',
  'CLERK',
  'Filed. About a minute to spare.',
  '',
  'EXT. COURTHOUSE STEPS - DAY',
  '',
  'Dana and Ben stand together, the fight between them finally settled.',
  '',
  'DANA',
  "I'm grateful you trusted me even when I made it hard.",
  '',
  'BEN',
  "We forgive each other for the fear. That part is over.",
].join('\n');

// ── COMPETENT (5) — real craft, real flaws ────────────────────────────────
// Same 10-scene skeleton as 'strong' (clock, clue, revelation, relationship
// arc) but each sample pays the clue off early (scene 6, ~60%) instead of at
// the climax, repeats a flat low-momentum beat across two scenes, drops one
// stock reassurance line, and resolves the relationship thinly rather than
// fully in Act 3.

const REASONABLE_DOUBT = [
  'INT. LAW OFFICE - NIGHT',
  '',
  'Alicia reviews a case file, the office nearly empty this late.',
  '',
  'ALICIA',
  'Everyone in this firm thinks this client is guilty.',
  '',
  'DEVON',
  "Maybe we're the only two who don't.",
  '',
  'INT. COURTHOUSE HALLWAY - DAY',
  '',
  'Devon checks the trial calendar; the case resumes in three days.',
  '',
  'DEVON',
  "Three days, Alicia, and we still don't have a witness.",
  '',
  'INT. COURTHOUSE HALLWAY - CONTINUOUS',
  '',
  'Alicia finds a witness statement that contradicts the police report.',
  '',
  'ALICIA',
  '"He was home by nine." Nobody flagged this before now.',
  '',
  'INT. LAW OFFICE - NIGHT',
  '',
  'Devon resents carrying four trials alone while Alicia was out last year.',
  '',
  'DEVON',
  "You took the leave and left me holding four trials by myself.",
  '',
  'ALICIA',
  "I needed the time, Devon, and I know that isn't a good enough reason.",
  '',
  'INT. COURTROOM - DAY',
  '',
  'The witness confirms the statement almost immediately once Alicia presents it.',
  '',
  'WITNESS',
  "Yes, that's exactly what I told the officer.",
  '',
  'INT. LAW OFFICE - NIGHT',
  '',
  'The alibi checks out this early, settling a question they expected to carry longer.',
  '',
  'ALICIA',
  '"He was home by nine" checks out. That settles the alibi, at least.',
  '',
  'DEVON',
  'Trust me, that alone should be enough.',
  '',
  'INT. LAW OFFICE - DAY',
  '',
  'They review the same notes again the next day, nothing new to add.',
  '',
  'DEVON',
  'Nothing new in the timeline, honestly.',
  '',
  'ALICIA',
  "Okay. We'll keep looking anyway.",
  '',
  'INT. COURTROOM - DAY',
  '',
  'The prosecutor produces new physical evidence the alibi alone can\'t answer.',
  '',
  'PROSECUTOR',
  "One statement doesn't change the physical evidence, counselor.",
  '',
  'INT. COURTROOM - CONTINUOUS',
  '',
  'The jury foreperson reads the verdict, the alibi having done its quiet work weeks earlier.',
  '',
  'FOREPERSON',
  'We find the defendant not guilty.',
  '',
  'INT. COURTHOUSE STEPS - DAY',
  '',
  'Alicia and Devon shake hands outside, the old grievance never fully addressed.',
  '',
  'ALICIA',
  "We got there. I'm glad you stuck with it.",
  '',
  'DEVON',
  'Yeah. Good enough for me.',
].join('\n');

const THANKSGIVING_MAYBE = [
  'INT. FARMHOUSE KITCHEN - DAY',
  '',
  'Nora chops vegetables while Mother sets the table around her.',
  '',
  'MOTHER',
  'You said you might not make it this year.',
  '',
  'NORA',
  "And yet here I am, so let's not argue before the guests arrive.",
  '',
  'INT. FARMHOUSE LIVING ROOM - DAY',
  '',
  'Sam checks the schedule board; the last bus back leaves at six sharp.',
  '',
  'SAM',
  "Last bus back is six sharp, so don't disappear on us again.",
  '',
  'INT. FARMHOUSE KITCHEN - MORNING',
  '',
  "Nora finds her father's recipe card tucked in a drawer she forgot existed.",
  '',
  'NORA',
  '"Add the sage last, always." He wrote notes on everything.',
  '',
  'INT. FARMHOUSE DINING ROOM - CONTINUOUS',
  '',
  'Sam resents handling their father\'s illness alone the year Nora left.',
  '',
  'SAM',
  "You left the year Dad got sick and I resent handling it alone.",
  '',
  'NORA',
  "I was scared, Sam, and I know that isn't a good enough reason.",
  '',
  'INT. FARMHOUSE PORCH - NIGHT',
  '',
  'Nora sits alone on the porch after dinner, mostly quiet reflection.',
  '',
  'NORA',
  'Maybe I should have come back sooner.',
  '',
  'INT. FARMHOUSE KITCHEN - CONTINUOUS',
  '',
  "Mother watches Nora read the recipe card, the question settled almost at once.",
  '',
  'MOTHER',
  "I'm glad you found that. He would have wanted you to have it.",
  '',
  'INT. FARMHOUSE PORCH - CONTINUOUS',
  '',
  'Sam joins her outside the next morning, the cold clearing both their heads.',
  '',
  'SAM',
  "I'm still angry, but I'm glad you came this year.",
  '',
  'INT. FARMHOUSE DINING ROOM - NIGHT',
  '',
  "Sam's phone buzzes: the six o'clock bus is running early, cutting the visit short.",
  '',
  'SAM',
  "Bus is running early. You'll have to decide fast.",
  '',
  'EXT. FARMHOUSE DRIVEWAY - DAY',
  '',
  'Nora loads her car to leave, the recipe card already settled, the grievance never quite closed.',
  '',
  'NORA',
  "I'll come back before next year. I promise this time.",
  '',
  'SAM',
  "Trust me, next time will be different.",
].join('\n');

const THE_DEAD_DROP = [
  'INT. EMBASSY BASEMENT - NIGHT',
  '',
  'Farrow checks a dead drop location against an old map.',
  '',
  'FARROW',
  "The handler should have made contact three days ago.",
  '',
  'OFFICER',
  "Whoever runs this network is careful.",
  '',
  'EXT. EMBASSY COURTYARD - NIGHT',
  '',
  "The officer marks the calendar: the network's extraction window closes by Friday.",
  '',
  'OFFICER',
  "We've got until Friday before this window shuts for good.",
  '',
  'INT. SAFEHOUSE - NIGHT',
  '',
  'Farrow finds an old surveillance note tucked inside a case folder.',
  '',
  'FARROW',
  '"Second page, same drop." Someone\'s been feeding us in pieces.',
  '',
  'INT. SAFEHOUSE - CONTINUOUS',
  '',
  'The officer resents being kept in the dark on three prior operations.',
  '',
  'OFFICER',
  "You've run three ops without telling me the real stakes.",
  '',
  'FARROW',
  "I was protecting the op, and you resent that I didn't trust you with it.",
  '',
  'EXT. TRAIN STATION - NIGHT',
  '',
  'They wait on the platform, nothing conclusive in what they already have.',
  '',
  'OFFICER',
  "Still nothing here we haven't already seen.",
  '',
  'INT. TRAIN CAR - CONTINUOUS',
  '',
  'The handler slips Farrow the second page almost as soon as they board.',
  '',
  'HANDLER',
  "Everything you need is on the second page.",
  '',
  'FARROW',
  'Trust me, this changes everything.',
  '',
  'INT. SAFEHOUSE - NIGHT',
  '',
  'They review the note again back at the safehouse, little left to add to it.',
  '',
  'OFFICER',
  'Nothing new in what it says, honestly.',
  '',
  'INT. EMBASSY OFFICE - DAY',
  '',
  'The attache stonewalls, buying time the second page already spent for them.',
  '',
  'ATTACHE',
  "You can't prove anything, Farrow.",
  '',
  'INT. EMBASSY OFFICE - CONTINUOUS',
  '',
  'Farrow lays the note on the desk; the attache finally goes quiet.',
  '',
  'FARROW',
  'I think I just did.',
  '',
  'EXT. EMBASSY COURTYARD - MORNING',
  '',
  'Farrow and the officer walk out together, the earlier resentment unspoken between them.',
  '',
  'OFFICER',
  "Glad that's over. I trust you knew what you were doing.",
  '',
  'FARROW',
  "Good enough. Let's not do that again.",
].join('\n');

const ENCORE = [
  'INT. CONSERVATORY HALL - DAY',
  '',
  'Priya rehearses a violin passage alone, the hall empty this early.',
  '',
  'PRIYA',
  'Three weeks until the competition and this passage still fights me.',
  '',
  'INT. CONSERVATORY HALLWAY - DAY',
  '',
  'Julian marks the same three weeks on his own calendar, unbothered.',
  '',
  'JULIAN',
  'Three weeks, Priya. I mastered that section months ago.',
  '',
  'INT. PRACTICE ROOM - DAY',
  '',
  "Priya finds an old recording of her teacher's own margin notes.",
  '',
  'PRIYA',
  '"Slow the bridge down, don\'t rush the turn." Her own handwriting.',
  '',
  'INT. TEACHER OFFICE - DAY',
  '',
  "Julian confronts Priya over her coldness since the last recital.",
  '',
  'JULIAN',
  "You've been cold to me since the last recital and I don't know why.",
  '',
  'PRIYA',
  "I was jealous, Julian, and I resent that I have to say that out loud.",
  '',
  'INT. PRACTICE ROOM - CONTINUOUS',
  '',
  'Priya practices the bridge section slowly, the room quiet around her.',
  '',
  'PRIYA',
  'Slower. Again.',
  '',
  'INT. TEACHER OFFICE - DAY',
  '',
  "The teacher confirms the margin note fixes it almost immediately.",
  '',
  'TEACHER',
  "Better. That's the note finally landing.",
  '',
  'JULIAN',
  "Trust me, you've got this now.",
  '',
  'INT. CONSERVATORY HALLWAY - DAY',
  '',
  'Priya and Julian pass each other again, still mostly cordial.',
  '',
  'JULIAN',
  'Good luck out there.',
  '',
  'PRIYA',
  'You too, Julian.',
  '',
  'INT. CONSERVATORY HALL - NIGHT',
  '',
  'The teacher admits she never actually won that competition herself, only placed second.',
  '',
  'TEACHER',
  "I never won it either. I've been teaching you my own regret.",
  '',
  'INT. CONCERT HALL - NIGHT',
  '',
  'Priya performs the bridge section on stage, competent, the emotional turn already spent.',
  '',
  'STAGEHAND',
  "That was the best I've heard you play it.",
  '',
  'INT. CONCERT HALL BACKSTAGE - NIGHT',
  '',
  'Julian congratulates Priya afterward, briefly, before heading off himself.',
  '',
  'JULIAN',
  'That bridge section. You finally got it.',
  '',
  'PRIYA',
  'Thanks. Every slow, boring rep of it.',
].join('\n');

const ZERO_DAY = [
  'INT. SECURITY OPERATIONS CENTER - NIGHT',
  '',
  'Nadia scans a wall of logs, most of it routine noise.',
  '',
  'NADIA',
  'Nothing unusual tonight. Same as every other Tuesday.',
  '',
  'INT. SOC - CONTINUOUS',
  '',
  "The manager checks the market calendar: open is six hours out.",
  '',
  'MANAGER',
  "Market open is in six hours. That's our whole window.",
  '',
  'INT. SOC - CONTINUOUS',
  '',
  'Nadia finds a hidden script buried in a scheduled task.',
  '',
  'NADIA',
  '"Payload triggers at market open." Someone timed this deliberately.',
  '',
  'INT. SOC BREAK ROOM - NIGHT',
  '',
  "The manager resents Nadia escalating over his head last quarter.",
  '',
  'MANAGER',
  "You escalated over my head last quarter and never told me why.",
  '',
  'NADIA',
  "I was covering the team, and you resent that I didn't loop you in.",
  '',
  'INT. SOC - DAY',
  '',
  'Nadia reviews the report again the next day, mostly procedural.',
  '',
  'NADIA',
  'Not that I can find yet.',
  '',
  'INT. SOC - NIGHT',
  '',
  'The script is disabled almost immediately once flagged, sooner than expected.',
  '',
  'NADIA',
  'Done. That was easier than I expected.',
  '',
  'MANAGER',
  "Trust me, that's the hard part handled.",
  '',
  'INT. SOC - DAY',
  '',
  'They review the logs once more the following shift, nothing new to report.',
  '',
  'MANAGER',
  'Anything else in the logs?',
  '',
  'NADIA',
  'Not that I can find yet, honestly.',
  '',
  'INT. DATA CENTER - NIGHT',
  '',
  'A second-stage payload surfaces that nobody caught the first time.',
  '',
  'NADIA',
  'Turns out that was only the decoy. The real payload is still live.',
  '',
  'INT. SOC - CONTINUOUS',
  '',
  'The dashboard clears, the second payload never fires, the tension already spent earlier.',
  '',
  'MANAGER',
  'Good work tonight, Nadia.',
  '',
  'INT. SOC - MORNING',
  '',
  'Nadia writes the final report as the day shift arrives.',
  '',
  'MANAGER',
  "Glad you caught it. I trust your instincts more than I let on.",
  '',
  'NADIA',
  "Good to know. Let's leave it there.",
].join('\n');

// ── WEAK (5) — same signals present, craft absent ─────────────────────────
// Every sample still carries a clock, a clue, and a relationship rupture (the
// controlled-richness constraint), but the clock gets stated once and never
// followed up on, the clue is addressed flatly with no reversal, a beat
// repeats near-verbatim across two scenes, and the relationship gets NO
// resolution — the pair simply parts on a non-committal line.

const YARD_SIGNS = [
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'Volunteers stack yard signs against a folding table.',
  '',
  'CANDIDATE',
  'We need more signs on Elm Street.',
  '',
  'MANAGER',
  "We'll get to it this week.",
  '',
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'The manager notes election day on the wall calendar, three weeks off.',
  '',
  'MANAGER',
  'Three weeks to election day. Plenty of time, probably.',
  '',
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'The candidate finds an old donor list with a line circled months ago.',
  '',
  'CANDIDATE',
  '"Call before the filing deadline." Somebody circled this months ago.',
  '',
  'EXT. TOWN SQUARE - DAY',
  '',
  'The manager resents the candidate cutting the ad budget without asking first.',
  '',
  'MANAGER',
  'You cut my ad budget without telling me and I found out from the vendor.',
  '',
  'CANDIDATE',
  "I made the call fast, and I didn't think to loop you in.",
  '',
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'The manager reviews the polling memo, numbers unchanged from last week.',
  '',
  'MANAGER',
  'Same numbers as before.',
  '',
  'CANDIDATE',
  'These things take time.',
  '',
  'INT. CAMPAIGN OFFICE - NIGHT',
  '',
  'The manager reviews the budget again, nothing alarming either way.',
  '',
  'MANAGER',
  'Same numbers as last week, more or less.',
  '',
  'CANDIDATE',
  'Good to hear, I suppose.',
  '',
  'EXT. TOWN SQUARE - DAY',
  '',
  'A debate happens offstage; the candidate reviews notes beforehand.',
  '',
  'CANDIDATE',
  "I think I'm ready for tonight.",
  '',
  'MANAGER',
  "You'll do fine.",
  '',
  'INT. CAMPAIGN OFFICE - NIGHT',
  '',
  'The debate results come in, unremarkable, the donor list still uncalled.',
  '',
  'MANAGER',
  'That went about as expected.',
  '',
  'CANDIDATE',
  'I suppose it did.',
  '',
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'The candidate finally calls the donor list; nothing comes of any of it.',
  '',
  'CANDIDATE',
  'Called everyone on that list. Nothing new, honestly.',
  '',
  'MANAGER',
  "Everything's fine either way.",
  '',
  'INT. CAMPAIGN OFFICE - NIGHT',
  '',
  'The results come in on a small television, the room watching quietly.',
  '',
  'MANAGER',
  "It's close. We'll know soon.",
  '',
  'CANDIDATE',
  "We'll see.",
].join('\n');

const MERGE = [
  'INT. CAR - DAY',
  '',
  'Priya drives while her father naps in the passenger seat.',
  '',
  'PRIYA',
  'Still a long way to go.',
  '',
  'INT. CAR - DAY',
  '',
  'Her father checks the clock; visiting hours end at eight sharp.',
  '',
  'FATHER',
  'Visiting hours end at eight. We should keep moving.',
  '',
  'INT. GAS STATION - DAY',
  '',
  'Priya finds an old photo in the glovebox while looking for napkins.',
  '',
  'PRIYA',
  '"Summer, the year everything changed." Written on the back, nothing else.',
  '',
  'INT. CAR - DAY',
  '',
  'Priya presses about the photo; her father shuts the question down at once.',
  '',
  'PRIYA',
  'You never told me why we stopped visiting that summer.',
  '',
  'FATHER',
  'Not now, Priya. I resent being asked in a moving car.',
  '',
  'INT. DINER - DAY',
  '',
  'They stop for food, mostly quiet over the meal.',
  '',
  'FATHER',
  "This place hasn't changed.",
  '',
  'PRIYA',
  'Nothing around here ever does.',
  '',
  'INT. CAR - DAY',
  '',
  'They keep driving, the radio playing quietly, more silence between them.',
  '',
  'FATHER',
  'You used to sing along to this station.',
  '',
  'PRIYA',
  'That was a long time ago.',
  '',
  'INT. MOTEL ROOM - NIGHT',
  '',
  'They check into a motel for the night, mostly routine.',
  '',
  'FATHER',
  "We'll finish the drive tomorrow.",
  '',
  'PRIYA',
  'Sounds fine to me.',
  '',
  'INT. CAR - DAY',
  '',
  'The last stretch of the drive passes quietly, eight already come and gone unremarked.',
  '',
  'FATHER',
  'Almost there now.',
  '',
  'PRIYA',
  'Finally.',
  '',
  'INT. HOSPITAL PARKING LOT - DAY',
  '',
  'Priya asks about the photo one last time; her father gives a flat non-answer.',
  '',
  'FATHER',
  "It's not worth digging up now, honestly.",
  '',
  'PRIYA',
  "Everything's fine. We don't have to talk about it.",
  '',
  'INT. HOSPITAL LOBBY - DAY',
  '',
  'They part at the elevator, the earlier question left exactly where it was.',
  '',
  'FATHER',
  'Take care of yourself out there.',
  '',
  'PRIYA',
  "You too. I'll call when I land.",
].join('\n');

const SPLITTING_THE_HOUSE = [
  'INT. MEDIATION OFFICE - DAY',
  '',
  'Two lawyers review a settlement folder across a conference table.',
  '',
  'MEDIATOR',
  "Let's go through the house first.",
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'The mediator notes the filing deadline: Friday, or the case reopens in January.',
  '',
  'MEDIATOR',
  "Friday, or this reopens in January. Let's not let that happen.",
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'Derek finds an old joint account statement neither of them remembers.',
  '',
  'DEREK',
  '"Balance transferred, no note." Neither of us remembers this one.',
  '',
  'INT. MEDIATION HALLWAY - DAY',
  '',
  'Laura resents Derek moving money out of that account years ago without telling her.',
  '',
  'LAURA',
  'You moved money out of that account and never once mentioned it.',
  '',
  'DEREK',
  "I panicked back then, and I resent being reminded of it now.",
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'They move to the furniture inventory, mostly routine back and forth.',
  '',
  'MEDIATOR',
  'Who keeps the dining set?',
  '',
  'DEREK',
  "Doesn't matter to me.",
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'They continue through the list of shared property, the same rhythm as before.',
  '',
  'LAURA',
  "I don't need the car either.",
  '',
  'DEREK',
  "Fine, I'll take it.",
  '',
  'INT. MEDIATION HALLWAY - DAY',
  '',
  'Derek and Laura wait outside during a recess, saying little.',
  '',
  'DEREK',
  'This is taking a while.',
  '',
  'LAURA',
  'It always does.',
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'They resume the session, Friday still on the calendar, still unaddressed directly.',
  '',
  'MEDIATOR',
  "Let's finalize the remaining accounts.",
  '',
  'INT. MEDIATION OFFICE - CONTINUOUS',
  '',
  'The old transfer turns out to be a rent payment from years back, nothing more.',
  '',
  'LAWYER',
  'Turned out to be rent from years back. Not worth revisiting, honestly.',
  '',
  'DEREK',
  "Everything's fine either way.",
  '',
  'EXT. MEDIATION OFFICE PARKING LOT - DAY',
  '',
  'They walk to separate cars, the earlier resentment never brought up again.',
  '',
  'DEREK',
  'Take care, Laura.',
  '',
  'LAURA',
  'You too, Derek.',
].join('\n');

const THE_VISIT = [
  'INT. NURSING HOME ROOM - DAY',
  '',
  "Elena sits beside her grandmother's bed, the television murmuring.",
  '',
  'ELENA',
  'I brought the photos you asked for.',
  '',
  'GRANDMOTHER',
  'Thank you, dear.',
  '',
  'INT. NURSING HOME HALLWAY - DAY',
  '',
  'A nurse mentions visiting hours end at four today.',
  '',
  'NURSE',
  'Visiting hours end at four today. Just so you know.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Elena reads an old letter pulled from a drawer.',
  '',
  'ELENA',
  '"Visit again soon." Just a short note, nothing more.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  "Grandmother resents Elena's eight-month absence, the silence between visits still raw.",
  '',
  'GRANDMOTHER',
  "You didn't visit for eight months and never called to explain.",
  '',
  'ELENA',
  "I was overwhelmed, and I resent that I let that become an excuse.",
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'They flip through the photo album together, mostly quiet commentary.',
  '',
  'GRANDMOTHER',
  'I remember that summer.',
  '',
  'ELENA',
  'Me too.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'They look through old boxes next, the same unhurried pace as before.',
  '',
  'GRANDMOTHER',
  "There's more in the closet, if you want to look.",
  '',
  'ELENA',
  'Maybe next time.',
  '',
  'INT. NURSING HOME CAFETERIA - DAY',
  '',
  'Elena and her grandmother share a quiet lunch.',
  '',
  'GRANDMOTHER',
  'The food here is fine, at least.',
  '',
  'ELENA',
  "That's good to hear.",
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Four o\'clock passes without either of them mentioning it.',
  '',
  'GRANDMOTHER',
  "I'm glad you came today.",
  '',
  'ELENA',
  "I'll keep coming.",
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Elena brings the old note up again; her grandmother brushes past it.',
  '',
  'GRANDMOTHER',
  'It was nothing important, honestly.',
  '',
  'ELENA',
  "Everything's fine. I'll visit again soon.",
  '',
  'EXT. NURSING HOME ENTRANCE - DAY',
  '',
  'Elena leaves for the day, the earlier absence never quite addressed.',
  '',
  'ELENA',
  "I'll see you next week.",
  '',
  'GRANDMOTHER',
  'Take care getting home.',
].join('\n');

const THE_CORNER_BOOTH = [
  'INT. DINER - DAY',
  '',
  'Maren wipes down the corner booth before the morning rush.',
  '',
  'MAREN',
  'Same booth, same regulars.',
  '',
  'TOM',
  'Morning, Maren.',
  '',
  'INT. DINER - DAY',
  '',
  'Tom mentions the diner closes early today, at three.',
  '',
  'TOM',
  'Closing at three today. Slow Tuesday, I guess.',
  '',
  'INT. DINER - DAY',
  '',
  'Maren finds an old note tucked behind the register.',
  '',
  'MAREN',
  '"Keep the corner booth open." Somebody wrote this years ago.',
  '',
  'INT. DINER - DAY',
  '',
  "Tom resents Maren forgetting his order after six years of the same booth.",
  '',
  'TOM',
  'You forgot my order yesterday after six years of the same booth.',
  '',
  'MAREN',
  "I was distracted, Tom, and I resent you keeping score over coffee.",
  '',
  'INT. DINER - DAY',
  '',
  'Maren brings Tom his coffee, small talk between them.',
  '',
  'TOM',
  'Slow morning out there.',
  '',
  'MAREN',
  'It usually is on Tuesdays.',
  '',
  'INT. DINER - DAY',
  '',
  'The lunch rush comes and goes, mostly uneventful, same as any other day.',
  '',
  'CUSTOMER',
  'Check, please, whenever you get a chance.',
  '',
  'MAREN',
  'Coming right up.',
  '',
  'INT. DINER - DAY',
  '',
  'Tom lingers after the rush, chatting with Maren.',
  '',
  'TOM',
  'Same time tomorrow?',
  '',
  'MAREN',
  'Same booth, probably.',
  '',
  'INT. DINER - DAY',
  '',
  'Three o\'clock passes and the diner stays open anyway, no one remarking on it.',
  '',
  'MAREN',
  "Guess we're not closing early after all.",
  '',
  'TOM',
  "Can't complain, though.",
  '',
  'INT. DINER - DAY',
  '',
  'Maren brings the old note up again; Tom shrugs it off entirely.',
  '',
  'TOM',
  'Probably just an old habit, honestly.',
  '',
  'MAREN',
  "Everything's fine. Same booth either way.",
  '',
  'INT. DINER - DAY',
  '',
  'The two continue their routine, the forgotten order never brought up again.',
  '',
  'TOM',
  'See you tomorrow, then.',
  '',
  'MAREN',
  'See you tomorrow.',
].join('\n');

// ── TROUBLED (5) — same signals present, pervasive craft failure ─────────
// Every sample still carries a clock, a clue, and a stated relationship
// grievance (the controlled-richness constraint), but the clock is
// contradicted (the deadline passes with zero consequence), the clue is a
// genuine orphan (mentioned exactly once, never again), four scenes recycle
// an identical "same as always" beat, the relationship gets zero movement,
// and the dialogue leans hard on the on-the-nose/cliche lexicon dialogue.ts
// and originality.ts already flag.

const THE_GRIFT = [
  'INT. MOTEL ROOM - DAY',
  '',
  'Ray counts a stack of bills at the table.',
  '',
  'RAY',
  'I feel so happy about this score, honestly.',
  '',
  'VIC',
  'I feel so happy too, honestly.',
  '',
  'INT. DINER - DAY',
  '',
  'Vic mentions the mark leaves town by Friday.',
  '',
  'VIC',
  'The mark leaves town by Friday. That\'s the whole window.',
  '',
  'INT. MOTEL ROOM - DAY',
  '',
  'Ray finds an old note in his jacket pocket.',
  '',
  'RAY',
  '"Meet at the usual place." Just an old note, nothing more.',
  '',
  'INT. DINER - DAY',
  '',
  'Vic and Ray state the same old grievance without ever moving past it.',
  '',
  'VIC',
  "You have no idea what I've been through to set this up, honestly.",
  '',
  'RAY',
  'Trust me on this, it will work out fine.',
  '',
  'INT. MOTEL ROOM - DAY',
  '',
  'Ray and Vic rehearse their cover story once more.',
  '',
  'RAY',
  'I feel so nervous about the mark noticing, honestly.',
  '',
  'VIC',
  "Everything's fine. Don't worry about it.",
  '',
  'INT. DINER - DAY',
  '',
  'The mark sits down, unaware, as Ray and Vic begin the pitch.',
  '',
  'MARK',
  'So what exactly are you two offering?',
  '',
  'RAY',
  "Trust me on this, it's a great opportunity.",
  '',
  'INT. MOTEL ROOM - DAY',
  '',
  'Friday comes and goes with no consequence at all for either of them.',
  '',
  'VIC',
  'Same as always, Ray. Nothing\'s changed.',
  '',
  'RAY',
  "Everything's fine. Same as always.",
  '',
  'INT. DINER - DAY',
  '',
  'Another identical shift passes at the same booth, nothing different from the last.',
  '',
  'RAY',
  'I feel so happy this is almost done, honestly.',
  '',
  'VIC',
  'I feel so happy too, honestly.',
  '',
  'INT. MOTEL ROOM - NIGHT',
  '',
  'Ray and Vic split the take from the mark, the old note never mentioned again.',
  '',
  'VIC',
  'I feel so happy this went fine, honestly.',
  '',
  'RAY',
  "Everything's fine. Same as always.",
  '',
  'INT. MOTEL ROOM - NIGHT',
  '',
  'Ray and Vic sound exactly as they did in the first scene, nothing between them changed.',
  '',
  'RAY',
  'I feel so happy about this score, honestly.',
  '',
  'VIC',
  'I feel so happy too, honestly. Same as always.',
].join('\n');

const ADRIFT = [
  'INT. LIFEBOAT - DAY',
  '',
  'Two survivors sit quietly in the drifting lifeboat.',
  '',
  'HALE',
  'I feel so scared out here, honestly.',
  '',
  'BRYCE',
  'I feel so scared too, honestly.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Bryce mentions rescue boats stop searching after three days.',
  '',
  'BRYCE',
  'Rescue boats stop searching after three days. That\'s the whole window.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Bryce finds an old photograph in his jacket, water-stained.',
  '',
  'BRYCE',
  '"Wish you were here." Just a note on the back, nothing else.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Hale and Bryce state the same old grievance without ever moving past it.',
  '',
  'HALE',
  "You have no idea what I've been through out here, honestly.",
  '',
  'BRYCE',
  "Trust me on this, we'll manage somehow.",
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Hale rations the last of the water, calm and matter-of-fact.',
  '',
  'HALE',
  'Still nothing but ocean.',
  '',
  'BRYCE',
  'Same as yesterday.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Another day passes, the two saying little, the pattern unbroken.',
  '',
  'HALE',
  'Still nothing but ocean.',
  '',
  'BRYCE',
  'Same as before.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'The three-day window has already passed with no consequence for either of them.',
  '',
  'HALE',
  "I feel so tired of waiting, honestly.",
  '',
  'BRYCE',
  "Don't worry about it. We'll be okay.",
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Another quiet day passes on the water, identical to the one before it.',
  '',
  'HALE',
  'Still nothing but ocean.',
  '',
  'BRYCE',
  'Same as always.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'A distant ship appears on the horizon, the photograph never mentioned again.',
  '',
  'HALE',
  'I feel so relieved, I suppose, honestly.',
  '',
  'BRYCE',
  "Everything's fine now, I guess.",
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Hale and Bryce sound exactly as they did in the first scene, nothing between them changed.',
  '',
  'BRYCE',
  'I feel so scared out here, honestly.',
  '',
  'HALE',
  'I feel so scared too, honestly. Same as always.',
].join('\n');

const LOCKDOWN = [
  'INT. PRISON CELL - DAY',
  '',
  'Two inmates sit on their bunks.',
  '',
  'DUKE',
  'I feel so bored in here, honestly.',
  '',
  'MOSS',
  'I feel so bored too, honestly.',
  '',
  'INT. PRISON YARD - DAY',
  '',
  'Moss mentions the transfer list posts Friday.',
  '',
  'MOSS',
  'The transfer list posts Friday. That\'s the whole window.',
  '',
  'INT. PRISON CELL - DAY',
  '',
  'Duke finds an old note tucked under his mattress.',
  '',
  'DUKE',
  '"Wait for the signal." Just a note, nothing more.',
  '',
  'INT. PRISON CAFETERIA - DAY',
  '',
  'Duke and Moss state the same old grievance without ever moving past it.',
  '',
  'MOSS',
  "You have no idea what I've been through in here, honestly.",
  '',
  'DUKE',
  "Trust me on this, it'll be fine.",
  '',
  'INT. PRISON YARD - DAY',
  '',
  'Another day in the yard passes, unchanged.',
  '',
  'DUKE',
  'Same yard, same fence.',
  '',
  'MOSS',
  'Same as every day.',
  '',
  'INT. PRISON CELL - DAY',
  '',
  'The two sit quietly in the cell again, the pattern unbroken.',
  '',
  'DUKE',
  'I feel so restless tonight, honestly.',
  '',
  'MOSS',
  "Everything's fine. Try to sleep.",
  '',
  'INT. PRISON YARD - DAY',
  '',
  "The transfer list Friday has already passed with no consequence for either of them.",
  '',
  'DUKE',
  'Same yard, same fence.',
  '',
  'MOSS',
  'Same as always.',
  '',
  'INT. PRISON CELL - DAY',
  '',
  'The routine continues, nothing new, the note never mentioned again.',
  '',
  'DUKE',
  "I feel so tired of waiting, honestly.",
  '',
  'MOSS',
  "Don't worry about it. Get some sleep.",
  '',
  'INT. PRISON CELL - NIGHT',
  '',
  'Duke and Moss sound exactly as they did in the first scene, nothing between them changed.',
  '',
  'DUKE',
  'I feel so bored in here, honestly.',
  '',
  'MOSS',
  'I feel so bored too, honestly. Same as always.',
].join('\n');

const WHITEOUT = [
  'INT. RANGER STATION - DAY',
  '',
  'Two rangers review a map of the mountain.',
  '',
  'KOVAC',
  'I feel so worried about the storm, honestly.',
  '',
  'ODOM',
  'I feel so worried too, honestly.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'Odom mentions the storm closes the pass by nightfall.',
  '',
  'ODOM',
  'The storm closes the pass by nightfall. That\'s the whole window.',
  '',
  'INT. RANGER STATION - DAY',
  '',
  'Kovac finds an old trail log in a drawer.',
  '',
  'KOVAC',
  '"Do not proceed past marker nine." Just a note, nothing more.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'Odom and Kovac state the same old grievance without ever moving past it.',
  '',
  'ODOM',
  'You are so brave for volunteering for this shift, honestly.',
  '',
  'KOVAC',
  "Trust me on this, we'll be fine.",
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'The hike continues, calm and unremarkable.',
  '',
  'KOVAC',
  'Still quiet out here.',
  '',
  'ODOM',
  'Same as yesterday.',
  '',
  'INT. RANGER STATION - DAY',
  '',
  'They review the radio log back at the station, the pattern unbroken.',
  '',
  'ODOM',
  'Nothing new to report.',
  '',
  'KOVAC',
  "Everything's fine, then.",
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'Nightfall has already closed the pass with no consequence for either of them.',
  '',
  'KOVAC',
  'Still quiet out here.',
  '',
  'ODOM',
  'Same as before.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'Another patrol passes without incident, the trail log never mentioned again.',
  '',
  'KOVAC',
  'Still quiet out here.',
  '',
  'ODOM',
  'Same as always.',
  '',
  'INT. RANGER STATION - NIGHT',
  '',
  'Kovac and Odom sound exactly as they did in the first scene, nothing between them changed.',
  '',
  'ODOM',
  'I feel so worried about the storm, honestly.',
  '',
  'KOVAC',
  'I feel so worried too, honestly. Same as always.',
].join('\n');

const FIREBREAK = [
  'INT. FIRE STATION - DAY',
  '',
  'Two firefighters check equipment before a shift.',
  '',
  'REESE',
  'I feel so anxious about the dry season, honestly.',
  '',
  'NOLAN',
  'I feel so anxious too, honestly.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'Nolan mentions the fire danger rating expires Friday.',
  '',
  'NOLAN',
  'The fire danger rating expires Friday. That\'s the whole window.',
  '',
  'INT. FIRE STATION - DAY',
  '',
  'Reese finds an old inspection note in a binder.',
  '',
  'REESE',
  '"Recheck the north line by Friday." Just a note, nothing more.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'Nolan and Reese state the same old grievance without ever moving past it.',
  '',
  'NOLAN',
  "You have no idea what I've been through on this ridge, honestly.",
  '',
  'REESE',
  'Trust me on this, the line will hold.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'The crew inspects the firebreak line, nothing eventful.',
  '',
  'REESE',
  'Still holding, same as last week.',
  '',
  'NOLAN',
  'Same as always.',
  '',
  'INT. FIRE STATION - DAY',
  '',
  "The crew logs the day's inspection, nothing new, the pattern unbroken.",
  '',
  'NOLAN',
  'Nothing to report today.',
  '',
  'REESE',
  "Everything's fine, then.",
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'Friday has already passed with no consequence for either of them.',
  '',
  'REESE',
  'Still holding, same as last week.',
  '',
  'NOLAN',
  'Same as before.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'Another inspection passes without incident, the note never mentioned again.',
  '',
  'REESE',
  'Still holding, same as last week.',
  '',
  'NOLAN',
  'Same as always.',
  '',
  'INT. FIRE STATION - NIGHT',
  '',
  'Reese and Nolan sound exactly as they did in the first scene, nothing between them changed.',
  '',
  'NOLAN',
  'I feel so anxious about the dry season, honestly.',
  '',
  'REESE',
  'I feel so anxious too, honestly. Same as always.',
].join('\n');

export const REFERENCE_CORPUS: CorpusSample[] = [
  { label: 'Low Tide', band: 'strong', fountain: LOW_TIDE },
  { label: 'Nine Minutes', band: 'strong', fountain: NINE_MINUTES },
  { label: 'The Long Game', band: 'strong', fountain: THE_LONG_GAME },
  { label: 'Second Wind', band: 'strong', fountain: SECOND_WIND },
  { label: 'Sunlight Clause', band: 'strong', fountain: SUNLIGHT_CLAUSE },

  { label: 'Reasonable Doubt', band: 'competent', fountain: REASONABLE_DOUBT },
  { label: 'Thanksgiving, Maybe', band: 'competent', fountain: THANKSGIVING_MAYBE },
  { label: 'The Dead Drop', band: 'competent', fountain: THE_DEAD_DROP },
  { label: 'Encore', band: 'competent', fountain: ENCORE },
  { label: 'Zero Day', band: 'competent', fountain: ZERO_DAY },

  { label: 'Yard Signs', band: 'weak', fountain: YARD_SIGNS },
  { label: 'Merge', band: 'weak', fountain: MERGE },
  { label: 'Splitting the House', band: 'weak', fountain: SPLITTING_THE_HOUSE },
  { label: 'The Visit', band: 'weak', fountain: THE_VISIT },
  { label: 'The Corner Booth', band: 'weak', fountain: THE_CORNER_BOOTH },

  { label: 'The Grift', band: 'troubled', fountain: THE_GRIFT },
  { label: 'Adrift', band: 'troubled', fountain: ADRIFT },
  { label: 'Lockdown', band: 'troubled', fountain: LOCKDOWN },
  { label: 'Whiteout', band: 'troubled', fountain: WHITEOUT },
  { label: 'Firebreak', band: 'troubled', fountain: FIREBREAK },
];
