// Script Doctor — calibration reference corpus (Deliverable 1 of the
// calibration feature; the distribution built from these samples lives in
// ./reference.ts, the percentile math in ./percentile.ts).
//
// ── What this is ──────────────────────────────────────────────────────────
// 20 ORIGINAL, hand-authored sample Fountain screenplays, deliberately
// spanning four quality bands (5 each): 'strong', 'competent', 'weak',
// 'troubled'. None of this is copied from — or based on — any real,
// produced, or copyrighted screenplay; every premise, character, and line of
// dialogue below was written for this corpus. This is a small, curated
// reference SET for relative calibration ("stronger than 74% of the
// reference set"), not a claim about "all produced screenplays" — see
// reference.ts's and percentile.ts's header comments for the honesty
// requirement this satisfies.
//
// ── How the bands are engineered, not just labeled ───────────────────────
// The 14-pass pipeline's critical/major rules (as opposed to its ~200+ minor
// prose-texture checks per file, which fire on ordinary prose regardless of
// quality band) are overwhelmingly driven by structural signals the
// fountain-analyzer derives from the text: escalating suspense with a single
// late peak, clue seed->payoff timing, revelation placement, clock/deadline
// follow-through, relationship-shift arcs (rupture + later resolution), and
// purpose diversity across scenes — plus a handful of literal lexicons
// (dialogue.ts's on-the-nose/as-you-know-Bob/trait-labeling phrasing,
// originality.ts's cliche/generic-descriptor/telegraphing phrases, voice.ts's
// tone-register and subtext lexicons). Each band below deliberately hits or
// misses those signals:
//   'strong'    — escalating tension to one late (>=85%) climax scene, a
//                 clue seeded early and paid off late (not too quick, not
//                 before the final stretch), a revelation past the midpoint,
//                 a clock mentioned in both halves, a relationship rupture
//                 that gets an Act 3 resolution, varied purposes and
//                 emotional shifts, distinct character registers, no
//                 cliche/on-the-nose/passive-voice stock phrases.
//   'competent' — the same skeleton with 2-3 real flaws grafted in (a clue
//                 that pays off too quickly, a flatter midsection, an
//                 occasional cliche line, thinner relationship movement) —
//                 recognizably good-faith craft, not a first draft.
//   'weak'      — flat/non-escalating suspense, no clock, thin or repeated
//                 purposes, minimal or absent relationship movement, no real
//                 reversal.
//   'troubled'  — deliberately flat suspense (no reversal at all), no
//                 revelations, an orphaned clue (seeded, never paid off),
//                 uniform scene purposes, on-the-nose/cliche-heavy dialogue,
//                 no relationship movement.
//
// Every sample is 8+ scenes (several are 12) so the per-scene structural
// signals above have room to actually register.

export type CorpusBand = 'strong' | 'competent' | 'weak' | 'troubled';

export interface CorpusSample {
  label: string;
  band: CorpusBand;
  fountain: string;
}

// ── STRONG (5) ───────────────────────────────────────────────────────────

const LOW_TIDE = [
  'INT. HARBOR NEWSROOM - DAY',
  '',
  'Whit reads the same paragraph for the third time. The harbor town outside sits quiet under fog.',
  '',
  'WHIT',
  "Nobody's checked the docks since the trawler stopped answering the radio.",
  '',
  'EDITOR',
  "It's a slow month, Whit, not a mystery. Let the harbor master handle it.",
  '',
  'EXT. FISH DOCKS - DAWN',
  '',
  'The harbor master checks his watch. Hours left before the tide erases the last set of footprints on the mudflat.',
  '',
  'HARBOR MASTER',
  'If we want anything off that boat, it has to be now.',
  '',
  'INT. TRAWLER CABIN - DAY',
  '',
  'Whit finds a torn ledger page wedged under the wheel. She reads it aloud.',
  '',
  'WHIT',
  '"The manifest never left the harbor." Someone wanted that found.',
  '',
  'INT. REYES HOUSE - KITCHEN - NIGHT',
  '',
  "Danny slams a drawer shut. Reyes stands across the counter, arms crossed, resentment plain on her face.",
  '',
  'DANNY',
  'You knew he worked that boat and you said nothing to me.',
  '',
  'REYES',
  "I was protecting you, Danny, and you're angry at the wrong person.",
  '',
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  'Reyes pins the ledger photo to the board next to a shipping manifest that does not match it.',
  '',
  'REYES',
  'Two sets of numbers for one cargo. Somebody built a second version of this boat.',
  '',
  'EXT. CANNERY LOADING DOCK - DUSK',
  '',
  'Reyes finds a second logbook hidden behind a loose brick, confirming what Danny confesses under the loading light.',
  '',
  'DANNY',
  "I signed for that cargo. I didn't know what was in the crates until it was already gone.",
  '',
  'INT. HARBOR MASTER OFFICE - NIGHT',
  '',
  'The harbor master turns the second logbook over in his hands. Turns out he stamped every falsified page himself.',
  '',
  'HARBOR MASTER',
  "I told myself it was just paperwork. It was never just paperwork.",
  '',
  'EXT. REYES HOUSE - PORCH - NIGHT',
  '',
  'Reyes and Danny sit in the quiet. The wind settles; the porch light hums, steady and calm after the shouting.',
  '',
  'DANNY',
  "I keep replaying the day he asked me to sign. I keep wishing I'd said no.",
  '',
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  'A tip comes in: hours left before the falsified cargo ships out under a new name. Reyes grabs her jacket.',
  '',
  'REYES',
  "If that container clears the breakwater, we lose the whole case. Move.",
  '',
  'EXT. CONTAINER YARD - NIGHT',
  '',
  'A forklift engine roars. Someone shouts. Reyes runs between the stacked containers, radio crackling, a floodlight swinging wild across the yard.',
  '',
  'REYES',
  'Stop the crane! Now!',
  '',
  'FOREMAN',
  "You're too late, it's already sealed—",
  '',
  'EXT. CONTAINER YARD - CONTINUOUS',
  '',
  'Whit finds the matching torn page taped inside the container door. "The manifest never left the harbor" — it never did; the crate was rerouted, not shipped.',
  '',
  'WHIT',
  'It was here the whole time. They just needed everyone looking at the water.',
  '',
  'EXT. REYES HOUSE - PORCH - MORNING',
  '',
  'Danny embraces Reyes on the porch steps, the harbor calm and gold behind them. Relief, finally, after months of silence.',
  '',
  'DANNY',
  "I'm grateful you never stopped looking. I trust you with the rest of it now.",
  '',
  'REYES',
  'We forgive each other and we start over. That part was never in question.',
].join('\n');

const NINE_MINUTES = [
  'INT. NEGOTIATION VAN - NIGHT',
  '',
  'Priya studies the bank floor plan taped to a laptop screen. Sam pours two coffees neither of them will drink.',
  '',
  'PRIYA',
  'Four hostages, one shooter, and a manager who thinks he can talk his way out.',
  '',
  'SAM',
  "Whatever you do in there, do it slowly. Marcus doesn't strike me as patient.",
  '',
  'INT. BANK LOBBY - NIGHT',
  '',
  "Marcus paces near the vault door. Nine minutes on the wall clock before SWAT's deadline expires.",
  '',
  'MARCUS',
  'Nine minutes. Somebody better start believing me.',
  '',
  'INT. NEGOTIATION VAN - CONTINUOUS',
  '',
  'Priya reads a name off a folder Sam hands her.',
  '',
  'SAM',
  'His daughter is in pediatric ICU three blocks from here. "He needs cash for a transplant he cannot get approved."',
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  'Marcus grips the phone. Priya\'s voice, calm, comes through the speaker.',
  '',
  'PRIYA',
  "Marcus, I know about your daughter. Let's find a way that doesn't end with you in a cell instead of that hospital.",
  '',
  'INT. BANK LOBBY - MOMENTS LATER',
  '',
  'One hostage faints. Marcus kneels beside her, torn between the gun and the woman on the floor.',
  '',
  'MARCUS',
  "I never wanted anyone hurt. I just needed enough time.",
  '',
  'INT. NEGOTIATION VAN - CONTINUOUS',
  '',
  'Sam and Priya argue in a hushed, furious whisper, an old wound between them surfacing again.',
  '',
  'SAM',
  "You promised me after the courthouse job you'd stop walking in without backup.",
  '',
  'PRIYA',
  "And you promised you'd trust my read on a room. Pick one, Sam.",
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  'Marcus turns out to be stalling for a reason nobody guessed: a second man in a guard uniform is already at the side exit.',
  '',
  'MARCUS',
  "It was never just me. My brother-in-law works the loan desk. He set this up months ago.",
  '',
  'INT. BANK VESTIBULE - CONTINUOUS',
  '',
  "The lobby goes quiet. Everyone holds still, the tension between one breath and the next.",
  '',
  'HOSTAGE',
  'Please. Just let us go home.',
  '',
  'INT. NEGOTIATION VAN - CONTINUOUS',
  '',
  'Two minutes left on the countdown. Sam reaches for the radio to call the breach team.',
  '',
  'SAM',
  "Two minutes. If you don't have him talking down by then, command takes the door.",
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  'Alarms blare. Marcus grabs a hostage by the arm, dragging her toward the side door as a guard shouts and glass shatters somewhere behind them.',
  '',
  'MARCUS',
  "Nobody move! I swear I'll do it!",
  '',
  'PRIYA (V.O.)',
  'Marcus, put it down. Your daughter needs her father, not a headline.',
  '',
  'INT. BANK LOBBY - CONTINUOUS',
  '',
  "The gun clatters to the floor. Marcus sinks to his knees, exhausted, the fight finally gone out of him.",
  '',
  'MARCUS',
  "Okay. Okay. Just get her the surgery. That's all I ever wanted.",
  '',
  'INT. HOSPITAL CORRIDOR - MORNING',
  '',
  'Priya and Sam sit together, quiet and calm, the case finally closed. Sam takes her hand.',
  '',
  'SAM',
  "I'm grateful you were right about the room. I should have trusted you from the start.",
  '',
  'PRIYA',
  'We forgive the mistakes. That was never the hard part.',
].join('\n');

const THE_LONG_GAME = [
  'INT. WAREHOUSE HIDEOUT - NIGHT',
  '',
  "Odell lays blueprints across a table, methodical, each corner weighted down with a coin.",
  '',
  'ODELL',
  'Three exits. Two guards. One camera blind spot for four seconds.',
  '',
  'CASS',
  "Four seconds is nothing, Odell, we go in loud or we don't go in at all.",
  '',
  'EXT. MUSEUM STREET - DUSK',
  '',
  'Cass clocks the guard rotation from a parked car. Sunrise is the deadline: the shipment leaves before sunrise or the job is dead.',
  '',
  'CASS',
  "Sunrise, Odell. That's the whole window.",
  '',
  'INT. RECORDS OFFICE - NIGHT',
  '',
  'Odell photographs a guard duty sheet, quiet and precise.',
  '',
  'ODELL',
  '"The vault opens at three." Somebody wrote the exact minute down for us.',
  '',
  'INT. HIDEOUT - KITCHEN - NIGHT',
  '',
  "Cass and Odell argue over an old betrayal neither has said aloud in years.",
  '',
  'CASS',
  "You left me holding the last job alone and you never once said you were sorry.",
  '',
  'ODELL',
  "I was protecting the crew, Cass, and you resent me for a decision that kept you out of prison.",
  '',
  'INT. HIDEOUT - NIGHT',
  '',
  'The crew rehearses the route on a chalk floor plan, timing each other with a stopwatch.',
  '',
  'ODELL',
  'Ninety seconds in the east corridor. Anything slower and the second guard clears the corner.',
  '',
  'EXT. MUSEUM ROOFTOP - NIGHT',
  '',
  "Cass discovers a second alarm panel nobody had mapped, confirming the job was compromised from the start.",
  '',
  'CASS',
  "Somebody sold us a floor plan from two years ago. This whole thing is wrong.",
  '',
  'INT. MUSEUM SERVER ROOM - NIGHT',
  '',
  "Odell finds the buyer's name on an internal memo. It was you all along feeding the museum our schedule.",
  '',
  'ODELL',
  "I knew it. Somebody on this crew has been talking.",
  '',
  'INT. HIDEOUT - NIGHT',
  '',
  'The room goes still, the accusation hanging over the table, nobody willing to move first.',
  '',
  'CASS',
  'Say it to my face, Odell, or don\'t say it at all.',
  '',
  'EXT. MUSEUM STREET - PRE-DAWN',
  '',
  'A rival crew arrives early, guns drawn, the alley suddenly loud with shouting and running boots.',
  '',
  'RIVAL LEADER',
  'Nobody touches that vault but us! Move!',
  '',
  'INT. MUSEUM VAULT CORRIDOR - CONTINUOUS',
  '',
  'Odell and Cass sprint the ninety-second corridor together, the vault door easing open exactly at three, just as the note promised.',
  '',
  'ODELL',
  'Go, go, now!',
  '',
  'EXT. SAFEHOUSE ROOFTOP - SUNRISE',
  '',
  'Cass and Odell watch the sun rise over the city, calm at last, the job finally behind them. Cass offers a hand.',
  '',
  'CASS',
  "I'm grateful you came back for me in that corridor. I forgive the rest of it.",
  '',
  'ODELL',
  'We trust each other again, starting now. That was always the long game.',
].join('\n');

const SECOND_WIND = [
  'INT. GYM - MORNING',
  '',
  'Theo wraps his own hands, slow, careful, the gym empty this early.',
  '',
  'THEO',
  "Nobody thinks a thirty-nine-year-old gets a second title shot.",
  '',
  'RUTH',
  "Then we make them regret underestimating you. That's the whole plan.",
  '',
  'EXT. BOARDWALK - DAWN',
  '',
  'Theo runs the pier at dawn. Six weeks left before the fight, and every mile counts now.',
  '',
  'RUTH',
  'Six weeks. We build the legs first, the chin later.',
  '',
  'INT. GYM OFFICE - DAY',
  '',
  'Ruth finds an old note in Theo\'s locker.',
  '',
  'RUTH',
  '"Never good enough for him." Your father wrote that on the back of your first fight poster.',
  '',
  'INT. THEO APARTMENT - NIGHT',
  '',
  "Theo and his brother Marcus argue about their father, years of resentment surfacing at once.",
  '',
  'MARCUS',
  "You still fight like you're trying to make him proud, and he's been gone eleven years.",
  '',
  'THEO',
  "I'm angry at a dead man, Marcus, and I don't know how else to let it go.",
  '',
  'INT. GYM - DAY',
  '',
  'Theo works the heavy bag, the midpoint of camp, form finally sharpening under Ruth\'s watch.',
  '',
  'RUTH',
  'That combination right there. That is the fight, Theo. Remember it.',
  '',
  'INT. GYM - NIGHT',
  '',
  'Ruth discovers the truth about the poster: Theo\'s father kept every clipping, hidden, never once showing them to his son.',
  '',
  'RUTH',
  "Turns out he kept every article about you in a shoebox. He was proud. He just never said it.",
  '',
  'THEO',
  "I knew it. I always hoped there was something, and nobody ever told me.",
  '',
  'INT. THEO APARTMENT - NIGHT',
  '',
  "Theo sits with the shoebox, quiet, the anger finally draining out of him.",
  '',
  'THEO',
  "I spent eleven years angry at a man who was proud of me the whole time.",
  '',
  'EXT. TRAINING CAMP - DAY',
  '',
  'A rival fighter\'s camera crew shows up uninvited, rattling Theo two weeks before the bout.',
  '',
  'RIVAL FIGHTER',
  "Two weeks, old man. Enjoy the attention while it lasts.",
  '',
  'INT. ARENA - LOCKER ROOM - NIGHT',
  '',
  'Marcus arrives unannounced, the shoebox under his arm, just before the final bell of camp.',
  '',
  'MARCUS',
  "I brought the rest of it. I should have given you this years ago.",
  '',
  'INT. ARENA - RING - NIGHT',
  '',
  'The bell rings. Theo and his opponent trade blows in the final round, the crowd roaring, blood on the canvas, everything on the line at once.',
  '',
  'CORNERMAN',
  "Thirty seconds! Finish it now!",
  '',
  'INT. ARENA - RING - CONTINUOUS',
  '',
  'Theo lands the combination Ruth drilled at the midpoint. The crowd goes silent, then erupts.',
  '',
  'ANNOUNCER',
  'And the new champion!',
  '',
  'INT. ARENA - CORRIDOR - NIGHT',
  '',
  'Theo, Ruth, and Marcus stand together, calm and quiet after the roar of the crowd. Marcus embraces his brother.',
  '',
  'MARCUS',
  "I'm proud of you. I should have said that a long time ago.",
  '',
  'THEO',
  "We forgive the years we lost. I trust we have plenty more ahead of us.",
].join('\n');

const SUNLIGHT_CLAUSE = [
  'INT. CHEMPLANT OFFICE - DAY',
  '',
  'Dana copies a stack of internal memos after hours, the building quiet around her.',
  '',
  'DANA',
  "Nobody outside this building knows what's in the runoff numbers.",
  '',
  'INT. LAW OFFICE - DAY',
  '',
  'Ben reviews a filing calendar taped to his monitor. The deadline for the injunction is one week away.',
  '',
  'BEN',
  "One week. If we miss the filing deadline, the plant runs through the summer unchecked.",
  '',
  'INT. DANA APARTMENT - NIGHT',
  '',
  'Dana finds an internal memo buried in an old email thread.',
  '',
  'DANA',
  '"The sunlight clause expires at midnight Friday." Someone buried this on purpose.',
  '',
  'INT. DANA APARTMENT - CONTINUOUS',
  '',
  "Dana's sister Rosa calls, furious that Dana risked her job without telling her first.",
  '',
  'ROSA',
  "You could lose everything and you didn't think to warn me?",
  '',
  'DANA',
  "I was afraid you'd talk me out of it, Rosa, and I resent that you might have been right.",
  '',
  'INT. LAW OFFICE - DAY',
  '',
  'Ben and Dana build the case at the midpoint, cross-referencing memos against the plant\'s public filings.',
  '',
  'BEN',
  'This paragraph right here. This is the whole case if we can prove intent.',
  '',
  'INT. CHEMPLANT EXECUTIVE OFFICE - NIGHT',
  '',
  'Ben discovers a signed authorization proving the executive knew about the runoff for a year before Dana ever found it.',
  '',
  'BEN',
  "Turns out they knew in March. Every month since has been a choice, not an accident.",
  '',
  'INT. LAW OFFICE - NIGHT',
  '',
  "The office goes quiet as the weight of the discovery settles over both of them.",
  '',
  'DANA',
  "I knew it. I hoped I was wrong, and I wasn't.",
  '',
  'EXT. CHEMPLANT PARKING LOT - NIGHT',
  '',
  'A company lawyer intercepts Dana, threatening a lawsuit if she testifies before the deadline.',
  '',
  'COMPANY LAWYER',
  "You testify, we bury you in litigation for a decade. Think carefully.",
  '',
  'INT. COURTHOUSE STEPS - MORNING',
  '',
  'Midnight Friday has come and gone. Reporters shout questions as Dana climbs the courthouse steps with minutes left before the clerk\'s window closes.',
  '',
  'REPORTER',
  'Dana, is it true the sunlight clause expired last night?',
  '',
  'INT. COURTHOUSE CLERK WINDOW - CONTINUOUS',
  '',
  'Ben slides the filing across the counter with seconds to spare, the clerk stamping it just before the window shuts.',
  '',
  'CLERK',
  'Filed. You made it with about a minute to spare.',
  '',
  'EXT. COURTHOUSE STEPS - DAY',
  '',
  'Rosa arrives, breathless, and embraces her sister on the steps, the fight between them finally settled.',
  '',
  'ROSA',
  "I'm proud of you, and I trust you more than I ever said out loud.",
  '',
  'DANA',
  'We forgive each other for the fear. That part is finally over.',
].join('\n');

// ── COMPETENT (5) — real craft, real flaws ────────────────────────────────
// Same structural DNA as 'strong' (clock, clue, revelation, relationship
// arc) but each sample drops 2-3 of those signals: a clue paid off almost
// immediately (PAYOFF_TOO_QUICK territory), a flatter midsection with
// repeated low-momentum purposes, an occasional stock phrase, or a
// relationship arc that never resolves in Act 3.

const REASONABLE_DOUBT = [
  'INT. LAW OFFICE - NIGHT',
  '',
  'Alicia reviews a case file, the office nearly empty.',
  '',
  'ALICIA',
  "Everyone in this firm thinks this client is guilty. Maybe they're right.",
  '',
  'INT. COURTHOUSE HALLWAY - DAY',
  '',
  'Alicia and her client wait outside the courtroom.',
  '',
  'CLIENT',
  "I didn't do it. I know how that sounds.",
  '',
  'INT. COURTHOUSE HALLWAY - CONTINUOUS',
  '',
  'Alicia finds a witness statement that contradicts the police report.',
  '',
  'ALICIA',
  '"He was home by nine." Nobody flagged this before now.',
  '',
  'INT. COURTROOM - DAY',
  '',
  'The witness confirms the statement almost immediately once Alicia presents it, barely a scene later.',
  '',
  'WITNESS',
  'Yes, that\'s exactly what I told the officer at the time.',
  '',
  'INT. COURTROOM - CONTINUOUS',
  '',
  'The prosecutor paces, unbothered.',
  '',
  'PROSECUTOR',
  "One statement doesn't change the physical evidence, counselor.",
  '',
  'INT. LAW OFFICE - NIGHT',
  '',
  'Alicia and her associate review notes without much happening.',
  '',
  'ASSOCIATE',
  'We should double check the timeline again.',
  '',
  'ALICIA',
  'Fine. We\'ll go over it tomorrow.',
  '',
  'INT. LAW OFFICE - DAY',
  '',
  'Alicia and the associate review notes again, the pace still slow.',
  '',
  'ASSOCIATE',
  'Nothing new in the timeline, honestly.',
  '',
  'ALICIA',
  "Okay. We'll keep looking anyway.",
  '',
  'INT. COURTROOM - DAY',
  '',
  'Alicia discovers the real timeline gap during cross-examination, turns out the officer mismarked the log by an hour.',
  '',
  'ALICIA',
  'Turns out the log was wrong the entire time, not the witness.',
  '',
  'INT. COURTROOM - CONTINUOUS',
  '',
  'The jury foreperson reads the verdict, tense silence across the gallery.',
  '',
  'FOREPERSON',
  'We find the defendant not guilty.',
  '',
  'INT. COURTHOUSE STEPS - DAY',
  '',
  'Alicia and her client shake hands outside, relief plain on both faces.',
  '',
  'CLIENT',
  "I'm grateful. I really am.",
  '',
  'ALICIA',
  "We got there. That's what matters.",
].join('\n');

const THANKSGIVING_MAYBE = [
  'INT. FARMHOUSE KITCHEN - DAY',
  '',
  'Nora chops vegetables while her mother sets the table around her.',
  '',
  'NORA',
  "I told you I might not make it this year.",
  '',
  'MOTHER',
  "And yet here you are, so let's not argue before the guests arrive.",
  '',
  'INT. FARMHOUSE LIVING ROOM - DAY',
  '',
  'Nora and her brother Sam catch up, mostly small talk.',
  '',
  'SAM',
  'How is the city treating you?',
  '',
  'NORA',
  "Busy. Same as always.",
  '',
  'INT. FARMHOUSE KITCHEN - DAY',
  '',
  'Nora and her mother talk quietly while dinner cooks.',
  '',
  'MOTHER',
  'Your father would have liked to see the table this full again.',
  '',
  'INT. FARMHOUSE DINING ROOM - DAY',
  '',
  'The family sits for dinner, mostly quiet, everyone tired from travel.',
  '',
  'SAM',
  'Pass the potatoes, please.',
  '',
  'NORA',
  'Here you go.',
  '',
  'INT. FARMHOUSE DINING ROOM - CONTINUOUS',
  '',
  'The dinner continues, still mostly quiet, an old grievance surfacing between Nora and Sam.',
  '',
  'SAM',
  "You left the year Dad got sick and I resent that I handled it alone.",
  '',
  'NORA',
  "I was scared, Sam, and I know that isn't a good enough reason.",
  '',
  'INT. FARMHOUSE PORCH - NIGHT',
  '',
  'Nora sits alone on the porch after dinner.',
  '',
  'NORA',
  "Maybe I should have come back sooner.",
  '',
  'INT. FARMHOUSE PORCH - CONTINUOUS',
  '',
  'Sam joins her outside, the cold clearing both their heads.',
  '',
  'SAM',
  "I'm still angry, but I'm glad you came this year.",
  '',
  'INT. FARMHOUSE KITCHEN - MORNING',
  '',
  'Nora finds her father\'s old recipe card tucked in a drawer she forgot existed.',
  '',
  'NORA',
  '"Add the sage last, always." He wrote notes on everything.',
  '',
  'INT. FARMHOUSE KITCHEN - CONTINUOUS',
  '',
  'The mother watches Nora read the card, quiet and moved.',
  '',
  'MOTHER',
  "I'm glad you found that. He would have wanted you to have it.",
  '',
  'EXT. FARMHOUSE DRIVEWAY - DAY',
  '',
  'Nora loads her car to leave, the visit ending on steadier ground than it started.',
  '',
  'NORA',
  "I'll come back before next year. I promise this time.",
].join('\n');

const THE_DEAD_DROP = [
  'INT. EMBASSY BASEMENT - NIGHT',
  '',
  'Farrow checks a dead drop location against an old map.',
  '',
  'FARROW',
  "The handler should have made contact three days ago.",
  '',
  'EXT. EMBASSY COURTYARD - NIGHT',
  '',
  'Farrow watches the gate from a parked car, nothing happening for a long stretch.',
  '',
  'FARROW',
  "Still nothing. Whoever runs this network is careful.",
  '',
  'INT. SAFEHOUSE - NIGHT',
  '',
  'Farrow briefs a junior officer, mostly procedural detail.',
  '',
  'OFFICER',
  'What do we do if the handler never shows?',
  '',
  'FARROW',
  "We wait. That's the job most nights.",
  '',
  'INT. SAFEHOUSE - CONTINUOUS',
  '',
  'The two review old surveillance photos, still nothing conclusive.',
  '',
  'OFFICER',
  'Nothing here we haven\'t already seen.',
  '',
  'FARROW',
  'Keep looking anyway.',
  '',
  'EXT. TRAIN STATION - NIGHT',
  '',
  'Farrow finally spots the handler boarding a late train, far later in the story than it should have taken.',
  '',
  'FARROW',
  "There. Finally. Move now before the doors close.",
  '',
  'INT. TRAIN CAR - CONTINUOUS',
  '',
  'The handler slips Farrow a folded note without a word exchanged.',
  '',
  'HANDLER',
  'Everything you need is on the second page.',
  '',
  'INT. SAFEHOUSE - NIGHT',
  '',
  'Farrow reads the note. Turns out the network was compromised from inside the embassy itself.',
  '',
  'FARROW',
  "Turns out our own attache sold the network out. I knew something felt wrong.",
  '',
  'INT. EMBASSY OFFICE - DAY',
  '',
  'Farrow confronts the attache directly, tense and quiet.',
  '',
  'ATTACHE',
  "You can't prove anything, Farrow.",
  '',
  'INT. EMBASSY OFFICE - CONTINUOUS',
  '',
  'Farrow lays the note on the desk, the attache finally silent.',
  '',
  'FARROW',
  'I think I just did.',
  '',
  'EXT. EMBASSY COURTYARD - MORNING',
  '',
  'Farrow and the junior officer walk out together, the case finally closed.',
  '',
  'OFFICER',
  "I'm glad that's over. I trust you knew what you were doing the whole time.",
].join('\n');

const ENCORE = [
  'INT. CONSERVATORY HALL - DAY',
  '',
  'Priya rehearses a violin passage alone, the hall empty.',
  '',
  'PRIYA',
  "Three weeks until the competition and this passage still fights me.",
  '',
  'INT. CONSERVATORY HALLWAY - DAY',
  '',
  'Priya passes her rival, Julian, practicing the same piece behind a closed door.',
  '',
  'JULIAN',
  "Still working on the bridge section, Priya? I mastered that months ago.",
  '',
  'INT. PRACTICE ROOM - DAY',
  '',
  'Priya finds an old recording of her teacher performing the same piece decades earlier.',
  '',
  'PRIYA',
  '"Slow the bridge down, don\'t rush the turn." Her own handwriting in the margins.',
  '',
  'INT. PRACTICE ROOM - CONTINUOUS',
  '',
  'Priya practices the bridge section slowly, the room quiet.',
  '',
  'PRIYA',
  'Slower. Again.',
  '',
  'INT. CONSERVATORY HALLWAY - DAY',
  '',
  'Priya and Julian pass each other again, still mostly cordial.',
  '',
  'JULIAN',
  'Good luck out there.',
  '',
  'PRIYA',
  'You too, Julian.',
  '',
  'INT. TEACHER OFFICE - DAY',
  '',
  'The teacher listens to Priya play the bridge, unmoved.',
  '',
  'TEACHER',
  'Better. Still not there.',
  '',
  'INT. CONSERVATORY HALL - NIGHT',
  '',
  'Priya discovers her teacher never actually won that competition decades ago, only placed second.',
  '',
  'TEACHER',
  "Turns out I never won it either. I've been teaching you my own regret.",
  '',
  'INT. CONSERVATORY HALL - CONTINUOUS',
  '',
  'Priya sits with that, quiet, unsure what to do with it.',
  '',
  'PRIYA',
  "I knew there was a reason you never talked about your own competitions.",
  '',
  'INT. CONCERT HALL - NIGHT',
  '',
  'Priya performs the bridge section on stage, the hall silent, the note landing clean this time.',
  '',
  'STAGEHAND',
  'That was the best I\'ve heard you play it.',
  '',
  'INT. CONCERT HALL BACKSTAGE - NIGHT',
  '',
  'Julian congratulates Priya afterward, genuinely this time.',
  '',
  'JULIAN',
  "That bridge section. You finally got it.",
  '',
  'PRIYA',
  "I'm grateful for the practice. Every slow, boring rep of it.",
].join('\n');

const ZERO_DAY = [
  'INT. SECURITY OPERATIONS CENTER - NIGHT',
  '',
  'Nadia scans a wall of logs, most of it routine noise.',
  '',
  'NADIA',
  "Nothing unusual tonight. Same as every other Tuesday.",
  '',
  'INT. SOC - CONTINUOUS',
  '',
  'An alert flashes on Nadia\'s screen, easy to miss among the routine noise.',
  '',
  'NADIA',
  'Odd. That port shouldn\'t be open.',
  '',
  'INT. SOC - CONTINUOUS',
  '',
  'Nadia finds a hidden script buried in a scheduled task.',
  '',
  'NADIA',
  '"Payload triggers at market open." Someone timed this deliberately.',
  '',
  'INT. SOC - CONTINUOUS',
  '',
  'The script is disabled almost immediately once found, barely any tension to it.',
  '',
  'NADIA',
  'Done. That was easier than I expected.',
  '',
  'INT. SOC BREAK ROOM - NIGHT',
  '',
  'Nadia and her manager discuss the incident report over coffee.',
  '',
  'MANAGER',
  'Write it up. Standard incident report.',
  '',
  'NADIA',
  'On it.',
  '',
  'INT. SOC - DAY',
  '',
  'Nadia reviews the report again the next day, mostly procedural.',
  '',
  'MANAGER',
  'Anything else in the logs?',
  '',
  'NADIA',
  'Not that I can find yet.',
  '',
  'INT. SOC - NIGHT',
  '',
  'Nadia discovers the script had a second stage nobody caught the first time.',
  '',
  'NADIA',
  "Turns out that was only the decoy. The real payload is still live.",
  '',
  'INT. DATA CENTER - NIGHT',
  '',
  'Nadia pulls a server offline manually, the room humming with cooling fans.',
  '',
  'TECHNICIAN',
  "You're cutting it close to market open.",
  '',
  'NADIA',
  'Then let\'s not waste the time we have left.',
  '',
  'INT. SOC - CONTINUOUS',
  '',
  'The dashboard clears. The second payload never fires.',
  '',
  'MANAGER',
  'Good work tonight, Nadia.',
  '',
  'INT. SOC - MORNING',
  '',
  'Nadia writes the final report as the day shift arrives.',
  '',
  'NADIA',
  "I'm relieved this is finally over, for tonight at least.",
].join('\n');

// ── WEAK (5) — flat structure, thin stakes, no real reversal ─────────────

const YARD_SIGNS = [
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'Volunteers stack yard signs against a folding table.',
  '',
  'CANDIDATE',
  'We need more signs on Elm Street.',
  '',
  'MANAGER',
  'We\'ll get to it this week.',
  '',
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'The candidate reviews a polling memo, numbers unchanged from last week.',
  '',
  'CANDIDATE',
  'Same numbers as before.',
  '',
  'MANAGER',
  'These things take time.',
  '',
  'EXT. TOWN SQUARE - DAY',
  '',
  'The candidate shakes hands at a small gathering, mostly routine.',
  '',
  'VOTER',
  'Good luck out there.',
  '',
  'CANDIDATE',
  'Thank you, I appreciate it.',
  '',
  'INT. CAMPAIGN OFFICE - DAY',
  '',
  'The manager reviews the budget, nothing alarming.',
  '',
  'MANAGER',
  'We\'re on track, more or less.',
  '',
  'CANDIDATE',
  'Good to hear.',
  '',
  'INT. CAMPAIGN OFFICE - NIGHT',
  '',
  'Volunteers fold flyers quietly, the office mostly empty.',
  '',
  'VOLUNTEER',
  'How many more of these tonight?',
  '',
  'MANAGER',
  'A few hundred, I think.',
  '',
  'EXT. TOWN SQUARE - DAY',
  '',
  'A debate happens offstage; the candidate reviews notes beforehand.',
  '',
  'CANDIDATE',
  'I think I\'m ready for tonight.',
  '',
  'MANAGER',
  'You\'ll do fine.',
  '',
  'INT. CAMPAIGN OFFICE - NIGHT',
  '',
  'The debate results come in, unremarkable.',
  '',
  'MANAGER',
  'That went about as expected.',
  '',
  'CANDIDATE',
  'I suppose it did.',
  '',
  'EXT. TOWN SQUARE - DAY',
  '',
  'Election day arrives, quiet, ordinary.',
  '',
  'VOTER',
  'Good luck today.',
  '',
  'CANDIDATE',
  'Thanks for coming out.',
  '',
  'INT. CAMPAIGN OFFICE - NIGHT',
  '',
  'The results come in on a small television, the room watching quietly.',
  '',
  'MANAGER',
  'It\'s close. We\'ll know soon.',
  '',
  'CANDIDATE',
  'We\'ll see.',
].join('\n');

const MERGE = [
  'INT. CAR - DAY',
  '',
  'Priya drives while her father naps in the passenger seat.',
  '',
  'PRIYA',
  'Still a long way to go.',
  '',
  'INT. CAR - DAY',
  '',
  'Her father wakes, and they talk about nothing in particular.',
  '',
  'FATHER',
  'How much further?',
  '',
  'PRIYA',
  'A few more hours.',
  '',
  'INT. DINER - DAY',
  '',
  'They stop for food, mostly quiet over the meal.',
  '',
  'FATHER',
  'This place hasn\'t changed.',
  '',
  'PRIYA',
  'Nothing around here ever does.',
  '',
  'INT. CAR - DAY',
  '',
  'They keep driving, the radio playing quietly.',
  '',
  'FATHER',
  'You used to sing along to this station.',
  '',
  'PRIYA',
  'That was a long time ago.',
  '',
  'INT. GAS STATION - DAY',
  '',
  'Priya finds an old photo in the glovebox while looking for napkins.',
  '',
  'PRIYA',
  '"Summer, the year everything changed." Written on the back, nothing else.',
  '',
  'INT. CAR - DAY',
  '',
  'Priya asks about the photo. Her father changes the subject.',
  '',
  'FATHER',
  'Not now, Priya. Let\'s just get back on the road.',
  '',
  'INT. CAR - DAY',
  '',
  'They continue in silence for a while.',
  '',
  'PRIYA',
  'Fine. We don\'t have to talk about it.',
  '',
  'INT. MOTEL ROOM - NIGHT',
  '',
  'They check into a motel for the night, mostly routine.',
  '',
  'FATHER',
  'We\'ll finish the drive tomorrow.',
  '',
  'PRIYA',
  'Sounds fine to me.',
  '',
  'INT. CAR - DAY',
  '',
  'The last stretch of the drive passes quietly.',
  '',
  'FATHER',
  'Almost there now.',
  '',
  'PRIYA',
  'Finally.',
].join('\n');

const SPLITTING_THE_HOUSE = [
  'INT. MEDIATION OFFICE - DAY',
  '',
  'Two lawyers review a settlement folder across a conference table.',
  '',
  'MEDIATOR',
  'Let\'s go through the house first.',
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'The two spouses sit at opposite ends of the table, saying little.',
  '',
  'DEREK',
  'Fine, take the house.',
  '',
  'LAURA',
  'Fine. I will.',
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'They move to the furniture inventory, mostly routine back and forth.',
  '',
  'MEDIATOR',
  'Who keeps the dining set?',
  '',
  'DEREK',
  'Doesn\'t matter to me.',
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'They continue through the list of shared property.',
  '',
  'LAURA',
  'I don\'t need the car either.',
  '',
  'DEREK',
  'Fine, I\'ll take it.',
  '',
  'INT. MEDIATION HALLWAY - DAY',
  '',
  'Derek and Laura wait outside during a recess, saying little.',
  '',
  'DEREK',
  'This is taking a while.',
  '',
  'LAURA',
  'It always does.',
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'They resume the session, still mostly procedural.',
  '',
  'MEDIATOR',
  'Let\'s finalize the remaining accounts.',
  '',
  'INT. MEDIATION OFFICE - CONTINUOUS',
  '',
  'The lawyers exchange paperwork, quiet and routine.',
  '',
  'LAWYER',
  'We\'ll have the final draft by Friday.',
  '',
  'INT. MEDIATION OFFICE - DAY',
  '',
  'Derek and Laura sign the settlement, mostly businesslike.',
  '',
  'DEREK',
  'That\'s everything, then.',
  '',
  'LAURA',
  'I suppose it is.',
  '',
  'EXT. MEDIATION OFFICE PARKING LOT - DAY',
  '',
  'They walk to separate cars without much said between them.',
  '',
  'DEREK',
  'Take care, Laura.',
  '',
  'LAURA',
  'You too, Derek.',
].join('\n');

const THE_VISIT = [
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Elena sits beside her grandmother\'s bed, the television murmuring.',
  '',
  'ELENA',
  'I brought the photos you asked for.',
  '',
  'GRANDMOTHER',
  'Thank you, dear.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Elena flips through the photo album with her grandmother, mostly quiet commentary.',
  '',
  'GRANDMOTHER',
  'I remember that summer.',
  '',
  'ELENA',
  'Me too.',
  '',
  'INT. NURSING HOME HALLWAY - DAY',
  '',
  'A nurse checks in briefly.',
  '',
  'NURSE',
  'She\'s doing about the same today.',
  '',
  'ELENA',
  'Thank you for letting me know.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Elena reads a letter from an old drawer, mostly ordinary correspondence.',
  '',
  'ELENA',
  '"Visit again soon." Just a short note, nothing more.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'Elena and her grandmother continue looking through old boxes.',
  '',
  'GRANDMOTHER',
  'There\'s more in the closet, if you want to look.',
  '',
  'ELENA',
  'Maybe next time.',
  '',
  'INT. NURSING HOME CAFETERIA - DAY',
  '',
  'Elena and her grandmother share a quiet lunch.',
  '',
  'GRANDMOTHER',
  'The food here is fine, at least.',
  '',
  'ELENA',
  'That\'s good to hear.',
  '',
  'INT. NURSING HOME ROOM - DAY',
  '',
  'They sit together in the afternoon light, saying little.',
  '',
  'GRANDMOTHER',
  'I\'m glad you came today.',
  '',
  'ELENA',
  'I\'ll keep coming.',
  '',
  'EXT. NURSING HOME ENTRANCE - DAY',
  '',
  'Elena leaves for the day, the visit ordinary and unremarkable.',
  '',
  'ELENA',
  'I\'ll see you next week.',
].join('\n');

const THE_CORNER_BOOTH = [
  'INT. DINER - DAY',
  '',
  'Maren wipes down the corner booth before the morning rush.',
  '',
  'MAREN',
  'Same booth, same regulars.',
  '',
  'INT. DINER - DAY',
  '',
  'A regular customer, Tom, sits at the counter reading the paper.',
  '',
  'TOM',
  'Morning, Maren.',
  '',
  'MAREN',
  'Morning, Tom. Usual?',
  '',
  'INT. DINER - DAY',
  '',
  'Maren brings Tom his coffee, small talk between them.',
  '',
  'TOM',
  'Slow morning out there.',
  '',
  'MAREN',
  'It usually is on Tuesdays.',
  '',
  'INT. DINER - DAY',
  '',
  'The lunch rush comes and goes, mostly uneventful.',
  '',
  'CUSTOMER',
  'Check, please, whenever you get a chance.',
  '',
  'MAREN',
  'Coming right up.',
  '',
  'INT. DINER - DAY',
  '',
  'Tom lingers after the rush, chatting with Maren.',
  '',
  'TOM',
  'Same time tomorrow?',
  '',
  'MAREN',
  'Same booth, probably.',
  '',
  'INT. DINER - DAY',
  '',
  'Another ordinary day passes at the diner.',
  '',
  'MAREN',
  'Another slow one.',
  '',
  'TOM',
  'Can\'t complain, though.',
  '',
  'INT. DINER - NIGHT',
  '',
  'Maren closes up for the night, wiping down the counter.',
  '',
  'MAREN',
  'Same routine, every night.',
  '',
  'INT. DINER - DAY',
  '',
  'Tom brings Maren a small gift, a paperback book she once mentioned.',
  '',
  'TOM',
  'Saw this and thought of you.',
  '',
  'MAREN',
  'That\'s kind of you, Tom.',
  '',
  'INT. DINER - DAY',
  '',
  'The two continue their easy routine, nothing dramatic between them.',
  '',
  'TOM',
  'See you tomorrow, then.',
  '',
  'MAREN',
  'See you tomorrow.',
].join('\n');

// ── TROUBLED (5) — deliberately flat, orphaned, cliche-heavy ─────────────
// Zero reversals, no revelations, an unresolved (never paid off) clue, a
// single repeated purpose, on-the-nose declarative dialogue, and several of
// originality.ts's/dialogue.ts's own cliche/generic-descriptor/on-the-nose
// stock phrases used verbatim on purpose.

const THE_GRIFT = [
  'INT. MOTEL ROOM - DAY',
  '',
  'Ray counts a stack of bills at the table.',
  '',
  'RAY',
  'I feel so happy about this score.',
  '',
  'INT. MOTEL ROOM - DAY',
  '',
  'Vic counts his share too.',
  '',
  'VIC',
  'I feel so happy too, honestly.',
  '',
  'INT. DINER - DAY',
  '',
  'Ray and Vic plan the next mark over coffee.',
  '',
  'RAY',
  'We need to talk about the next job.',
  '',
  'VIC',
  'It\'s not what it looks like, this one is simple.',
  '',
  'INT. MOTEL ROOM - DAY',
  '',
  'Ray finds an old note in his jacket pocket.',
  '',
  'RAY',
  '"Meet at the usual place." Just an old note, nothing more.',
  '',
  'INT. DINER - DAY',
  '',
  'Ray and Vic go over the plan again, the same beats as before.',
  '',
  'VIC',
  'You have no idea what I\'ve been through to set this up.',
  '',
  'RAY',
  'Trust me on this, it will work out fine.',
  '',
  'INT. MOTEL ROOM - DAY',
  '',
  'Ray and Vic rehearse their cover story once more.',
  '',
  'RAY',
  'I feel so nervous about the mark noticing.',
  '',
  'VIC',
  'Everything\'s fine. Don\'t worry about it.',
  '',
  'INT. DINER - DAY',
  '',
  'The mark sits down, unaware, as Ray and Vic begin the pitch.',
  '',
  'MARK',
  'So what exactly are you two offering?',
  '',
  'RAY',
  'Trust me on this, it\'s a great opportunity.',
  '',
  'INT. MOTEL ROOM - NIGHT',
  '',
  'Ray and Vic split the take from the mark, calm and businesslike.',
  '',
  'VIC',
  'I feel so happy this went fine.',
  '',
  'RAY',
  'Everything\'s fine. Same as always.',
].join('\n');

const ADRIFT = [
  'INT. LIFEBOAT - DAY',
  '',
  'Two survivors sit quietly in the drifting lifeboat.',
  '',
  'HALE',
  'I feel so scared out here.',
  '',
  'BRYCE',
  'I feel so scared too, honestly.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'The boat drifts further, nothing changing.',
  '',
  'HALE',
  'Still nothing but ocean.',
  '',
  'BRYCE',
  'Same as yesterday.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Hale rations the last of the water, calm and matter-of-fact.',
  '',
  'HALE',
  'This is the last of it.',
  '',
  'BRYCE',
  'Everything\'s fine. We\'ll manage somehow.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Another day passes, the two saying little.',
  '',
  'HALE',
  'Still nothing but ocean.',
  '',
  'BRYCE',
  'Same as before.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Bryce finds an old photograph in his jacket, water-stained.',
  '',
  'BRYCE',
  '"Wish you were here." Just a note on the back, nothing else.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'The two continue drifting, the mood unchanged.',
  '',
  'HALE',
  'I feel so tired of waiting.',
  '',
  'BRYCE',
  'Don\'t worry about it. We\'ll be okay.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'Another quiet day passes on the water.',
  '',
  'HALE',
  'Still nothing but ocean.',
  '',
  'BRYCE',
  'Same as always.',
  '',
  'INT. LIFEBOAT - DAY',
  '',
  'A distant ship finally appears on the horizon, though neither reacts with much urgency.',
  '',
  'HALE',
  'I feel so relieved, I suppose.',
  '',
  'BRYCE',
  'Everything\'s fine now, I guess.',
].join('\n');

const LOCKDOWN = [
  'INT. PRISON CELL - DAY',
  '',
  'Two inmates sit on their bunks.',
  '',
  'DUKE',
  'I feel so bored in here.',
  '',
  'MOSS',
  'I feel so bored too, honestly.',
  '',
  'INT. PRISON YARD - DAY',
  '',
  'The inmates walk the yard, saying little.',
  '',
  'DUKE',
  'Same yard, same fence.',
  '',
  'MOSS',
  'Same as every day.',
  '',
  'INT. PRISON CELL - DAY',
  '',
  'Duke finds an old note tucked under his mattress.',
  '',
  'DUKE',
  '"Wait for the signal." Just a note, nothing more.',
  '',
  'INT. PRISON CAFETERIA - DAY',
  '',
  'The two eat lunch, discussing nothing in particular.',
  '',
  'MOSS',
  'You have no idea what I\'ve been through in here.',
  '',
  'DUKE',
  'Trust me on this, it\'ll be fine.',
  '',
  'INT. PRISON YARD - DAY',
  '',
  'Another day in the yard passes, unchanged.',
  '',
  'DUKE',
  'Same yard, same fence.',
  '',
  'MOSS',
  'Same as always.',
  '',
  'INT. PRISON CELL - DAY',
  '',
  'The two sit quietly in the cell again.',
  '',
  'DUKE',
  'I feel so restless tonight.',
  '',
  'MOSS',
  'Everything\'s fine. Try to sleep.',
  '',
  'INT. PRISON YARD - DAY',
  '',
  'The yard routine continues, nothing new.',
  '',
  'DUKE',
  'Same yard, same fence.',
  '',
  'MOSS',
  'Same as before.',
  '',
  'INT. PRISON CELL - NIGHT',
  '',
  'The lights go out for the night, the two settling in.',
  '',
  'DUKE',
  'I feel so tired of waiting for something to change.',
  '',
  'MOSS',
  'Don\'t worry about it. Get some sleep.',
].join('\n');

const WHITEOUT = [
  'INT. RANGER STATION - DAY',
  '',
  'Two rangers review a map of the mountain.',
  '',
  'KOVAC',
  'I feel so worried about the storm.',
  '',
  'ODOM',
  'I feel so worried too, honestly.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'The rangers hike through calm, unremarkable terrain.',
  '',
  'KOVAC',
  'Still quiet out here.',
  '',
  'ODOM',
  'Same as yesterday.',
  '',
  'INT. RANGER STATION - DAY',
  '',
  'Kovac finds an old trail log in a drawer.',
  '',
  'KOVAC',
  '"Do not proceed past marker nine." Just a note, nothing more.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'You are so brave for volunteering for this shift, Odom says to Kovac.',
  '',
  'ODOM',
  'You are so brave, Kovac, honestly.',
  '',
  'KOVAC',
  'Trust me on this, we\'ll be fine.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'The hike continues, calm and unremarkable.',
  '',
  'KOVAC',
  'Still quiet out here.',
  '',
  'ODOM',
  'Same as before.',
  '',
  'INT. RANGER STATION - DAY',
  '',
  'The two review the radio log back at the station.',
  '',
  'ODOM',
  'Nothing new to report.',
  '',
  'KOVAC',
  'Everything\'s fine, then.',
  '',
  'EXT. MOUNTAIN TRAIL - DAY',
  '',
  'Another patrol passes without incident.',
  '',
  'KOVAC',
  'Still quiet out here.',
  '',
  'ODOM',
  'Same as always.',
  '',
  'INT. RANGER STATION - NIGHT',
  '',
  'The rangers log off for the night, routine and calm.',
  '',
  'KOVAC',
  'I feel so relieved this shift is over.',
  '',
  'ODOM',
  'Everything\'s fine. See you tomorrow.',
].join('\n');

const FIREBREAK = [
  'INT. FIRE STATION - DAY',
  '',
  'Two firefighters check equipment before a shift.',
  '',
  'REESE',
  'I feel so anxious about the dry season.',
  '',
  'NOLAN',
  'I feel so anxious too, honestly.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'The crew inspects the firebreak line, nothing eventful.',
  '',
  'REESE',
  'Still holding, same as last week.',
  '',
  'NOLAN',
  'Same as always.',
  '',
  'INT. FIRE STATION - DAY',
  '',
  'Reese finds an old inspection note in a binder.',
  '',
  'REESE',
  '"Recheck the north line by Friday." Just a note, nothing more.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'A truck was found abandoned near the ridge by another crew, the report was filed without much comment.',
  '',
  'NOLAN',
  'You have no idea what I\'ve been through on this ridge.',
  '',
  'REESE',
  'Trust me on this, the line will hold.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'The inspection continues, calm and routine.',
  '',
  'REESE',
  'Still holding, same as last week.',
  '',
  'NOLAN',
  'Same as before.',
  '',
  'INT. FIRE STATION - DAY',
  '',
  'The crew logs the day\'s inspection, nothing new.',
  '',
  'NOLAN',
  'Nothing to report today.',
  '',
  'REESE',
  'Everything\'s fine, then.',
  '',
  'EXT. RIDGE ROAD - DAY',
  '',
  'Another inspection passes without incident.',
  '',
  'REESE',
  'Still holding, same as last week.',
  '',
  'NOLAN',
  'Same as always.',
  '',
  'INT. FIRE STATION - NIGHT',
  '',
  'The crew ends the shift, routine and calm.',
  '',
  'REESE',
  'I feel so relieved the line is holding.',
  '',
  'NOLAN',
  'Everything\'s fine. See you next shift.',
].join('\n');

export const REFERENCE_CORPUS: CorpusSample[] = [
  { label: 'Low Tide', band: 'strong', fountain: LOW_TIDE },
  { label: 'Nine Minutes', band: 'strong', fountain: NINE_MINUTES },
  { label: 'The Long Game', band: 'strong', fountain: THE_LONG_GAME },
  { label: 'Second Wind', band: 'strong', fountain: SECOND_WIND },
  { label: 'Sunlight Clause', band: 'strong', fountain: SUNLIGHT_CLAUSE },

  { label: 'Reasonable Doubt', band: 'competent', fountain: REASONABLE_DOUBT },
  { label: 'Thanksgiving, Maybe', band: 'competent', fountain: THANKSGIVING_MAYBE },
  { label: 'The Dead Drop', band: 'competent', fountain: THE_DEAD_DROP },
  { label: 'Encore', band: 'competent', fountain: ENCORE },
  { label: 'Zero Day', band: 'competent', fountain: ZERO_DAY },

  { label: 'Yard Signs', band: 'weak', fountain: YARD_SIGNS },
  { label: 'Merge', band: 'weak', fountain: MERGE },
  { label: 'Splitting the House', band: 'weak', fountain: SPLITTING_THE_HOUSE },
  { label: 'The Visit', band: 'weak', fountain: THE_VISIT },
  { label: 'The Corner Booth', band: 'weak', fountain: THE_CORNER_BOOTH },

  { label: 'The Grift', band: 'troubled', fountain: THE_GRIFT },
  { label: 'Adrift', band: 'troubled', fountain: ADRIFT },
  { label: 'Lockdown', band: 'troubled', fountain: LOCKDOWN },
  { label: 'Whiteout', band: 'troubled', fountain: WHITEOUT },
  { label: 'Firebreak', band: 'troubled', fountain: FIREBREAK },
];
