// Script Doctor — the DISCRIMINATION HARNESS corpus (Run 18-γ).
//
// ── What this is, and why it's separate from calibration/corpus.ts ────────
// corpus.ts's 20 samples exist to build a RELATIVE percentile distribution
// ("stronger than 74% of the reference set") under a CONTROLLED-RICHNESS
// design: every sample shares the same 10-scene skeleton and ~300-360 word
// budget so richness can't confound the band-ordering measurement (see that
// file's header). This file answers a different, narrower question: does
// the health formula reward good WRITING CRAFT over bad writing craft when
// everything else about the two scripts — premise, scene count, word count,
// structural beats — is held equal? That is a per-axis A/B test, not a
// distribution, so it needs PAIRS, not bands.
//
// The motivating finding: an adversarial reviewer submitted a deliberately
// flat, on-the-nose, passive-protagonist script that scored 78.7, then a
// genuinely well-crafted subtextual scene (real stakes, active protagonist,
// elliptical dialogue, ironic ending) that scored 72 — LOWER. The health
// score inverted on exactly the writing it exists to reward. Nothing in CI
// caught that class of failure before this file existed.
//
// ── Design ─────────────────────────────────────────────────────────────
// 6 pairs, 12 scripts. Each pair tells the SAME underlying story premise
// twice — once written well on one craft axis, once written poorly on that
// SAME axis — holding scene count (6-10) and word count (400-800,
// length-matched within ~15% within each pair) constant, so a health-score
// gap can only be explained by the axis under test, not by length or
// subject matter. The "good" half of every pair is written as a
// screenwriter would actually write it (specific, visual, subtextual) — a
// strawman-easy "good" half would make this harness worthless the moment a
// real regression needed catching.
//
//   1. subtext-vs-on-the-nose            — elliptical professional dialogue
//                                           vs characters narrating feelings
//                                           and stakes aloud.
//   2. active-vs-passive-protagonist     — protagonist drives every
//                                           decision vs things happen to her
//                                           while others decide and act.
//   3. escalation-vs-flat-repetition     — rising stakes with a genuine
//                                           reversal vs the same beat
//                                           repeated at flat intensity.
//   4. setup-payoff-vs-orphaned-setups   — two planted details (a dead
//                                           camera/elevator, a guard's
//                                           tremor) both pay off vs both
//                                           planted and never fired.
//   5. dramatized-vs-told-exposition     — the conspiracy is revealed
//                                           through confrontation and
//                                           action vs characters reciting
//                                           it to each other in full
//                                           sentences ("as you know...").
//   6. composite-reviewer-scenario       — the reviewer's original finding,
//                                           reconstructed: one script
//                                           combining all five virtues
//                                           above vs one combining all five
//                                           failures, matched premise and
//                                           size.
//
// Each script is 6-10 scenes and 400-800 words. Do not add absolute score
// assertions against these pairs — the surrounding formula (doctor.ts,
// fountain-analyzer.ts, the revision passes) is under active concurrent
// development; only RELATIVE (good > bad) comparisons survive that
// evolution. See tests/core/discrimination.test.ts for the assertions and
// the honest per-pair pass/todo ledger.

export type DiscriminationAxis =
  | 'subtext-vs-on-the-nose'
  | 'active-vs-passive-protagonist'
  | 'escalation-vs-flat-repetition'
  | 'setup-payoff-vs-orphaned-setups'
  | 'dramatized-vs-told-exposition'
  | 'composite-reviewer-scenario';

export interface DiscriminationScript {
  label: string;
  fountain: string;
}

export interface DiscriminationPair {
  id: string;
  axis: DiscriminationAxis;
  /** One-line description of what separates the good half from the bad
   *  half, for failure-message context. */
  description: string;
  good: DiscriminationScript;
  bad: DiscriminationScript;
}

// ── Pair 1 — subtext vs on-the-nose ───────────────────────────────────────
// Same premise (an ER surgeon and the nurse she used to love, working a
// crashing patient together): the good half lets the history surface
// through professional shorthand and withheld beats; the bad half has both
// characters narrate their feelings and the stakes in full sentences.

const PAIR1_GOOD = [
  'INT. HOSPITAL - SCRUB ROOM - NIGHT',
  '',
  'Dr. ELENA CRUZ scrubs past the elbow, longer than she needs to, watching suds spiral down the drain. Nurse SAM ORTIZ ties his mask in the mirror, watching her instead.',
  '',
  'SAM',
  "Table four's the one from before.",
  '',
  'ELENA',
  'I know which table it is.',
  '',
  'SAM',
  'Just saying it out loud.',
  '',
  'ELENA',
  "You don't have to.",
  '',
  'He hands her a fresh towel before she reaches for one.',
  '',
  'INT. OPERATING ROOM - CONTINUOUS',
  '',
  "Machines hum. Elena's hands are steady; her eyes aren't. Sam places the retractor in her palm before she asks for it, then adjusts the overhead light to the angle she likes without being told.",
  '',
  'ELENA',
  'You always did that. Before I even asked.',
  '',
  'SAM',
  'Somebody has to keep track of what you need.',
  '',
  'ELENA',
  'Somebody used to.',
  '',
  "Sam doesn't answer that one.",
  '',
  'INT. OPERATING ROOM - LATER',
  '',
  "The monitor SCREAMS. Blood pressure crashing. Elena's hands go still one beat too long, fixed on a bleeder she can't quite reach.",
  '',
  'SAM',
  'Elena.',
  '',
  'ELENA',
  'I heard it the first time.',
  '',
  'She moves. Fast, sure, furious with herself. Sam is already threading suction into the field before she calls for it.',
  '',
  'INT. OPERATING ROOM - CONTINUOUS',
  '',
  "Sam clamps a bleeder Elena can't reach. Their eyes meet over the open chest cavity — old ground, wordless, the kind of look that used to mean something else in a different room.",
  '',
  'ELENA',
  "Last time I froze like that, you weren't in the room.",
  '',
  'SAM',
  "I know exactly where I wasn't.",
  '',
  'ELENA',
  "That's not what I said.",
  '',
  'SAM',
  "It's what you meant.",
  '',
  'INT. OPERATING ROOM - CONTINUOUS',
  '',
  "The line flattens, then holds. Elena exhales through her mask, shoulders dropping an inch. Sam doesn't look away from the monitor, like looking away might undo it.",
  '',
  'SAM',
  'There it is.',
  '',
  'ELENA',
  'There it is.',
  '',
  'Neither of them moves to be the first to step back from the table.',
  '',
  'INT. HOSPITAL - HALLWAY - NIGHT',
  '',
  "Elena peels off her gloves outside, dropping them in the bin one at a time. Sam leans against the wall a few feet off, not quite leaving, not quite staying either.",
  '',
  'SAM',
  'You did good in there.',
  '',
  'ELENA',
  'We did.',
  '',
  'SAM',
  "That's not what I said.",
  '',
  'ELENA',
  "It's what you meant.",
  '',
  'He almost says something else. Does not.',
  '',
  'EXT. HOSPITAL - PARKING GARAGE - NIGHT',
  '',
  "Elena finds her keys at the bottom of her bag. Sam's car idles two spots down, headlights off, engine running longer than it needs to. He waits until she's inside hers before he pulls out first, the way he always used to.",
].join('\n');

const PAIR1_BAD = [
  'INT. HOSPITAL - SCRUB ROOM - NIGHT',
  '',
  'Dr. ELENA CRUZ scrubs her hands at the sink. Nurse SAM ORTIZ ties his mask, glancing at her the whole time.',
  '',
  'SAM',
  'I still have feelings for you, Elena, even after everything that happened between us.',
  '',
  'ELENA',
  'I know you do, Sam, and honestly, it hurts to work with you every single day.',
  '',
  'SAM',
  'This patient is critical. We need to focus, even though our history makes that really hard for both of us.',
  '',
  'ELENA',
  "You're right. Let's just get through this surgery and deal with our feelings later.",
  '',
  'INT. OPERATING ROOM - CONTINUOUS',
  '',
  'Machines hum steadily in the background.',
  '',
  'ELENA',
  "I'm still upset that you chose your job over our relationship two years ago, Sam.",
  '',
  'SAM',
  "That's not fair. I was trying to protect you from getting hurt again, that's all.",
  '',
  'ELENA',
  'Well, it hurt anyway, Sam. It hurt a lot, more than you probably realize.',
  '',
  'SAM',
  "I know. I think about that mistake constantly, if I'm being completely honest with you.",
  '',
  'INT. OPERATING ROOM - LATER',
  '',
  'The monitor beeps loudly, warning everyone of danger.',
  '',
  'SAM',
  'Elena, the blood pressure is dropping fast! This is a life or death situation right now!',
  '',
  'ELENA',
  "I'm scared we're going to lose him, just like we lost the last patient we worked on together.",
  '',
  'SAM',
  'Try not to think about that right now. We need to stay calm and focused on saving this man.',
  '',
  'INT. OPERATING ROOM - CONTINUOUS',
  '',
  'SAM',
  "I remember that day perfectly, Elena. You blamed yourself, and I felt so guilty I wasn't there for you.",
  '',
  'ELENA',
  "I'm still angry about that, Sam, but I also still care about you deep down inside.",
  '',
  'SAM',
  "I care about you too. I never stopped, even when I said things I didn't mean.",
  '',
  'INT. OPERATING ROOM - CONTINUOUS',
  '',
  'The heart monitor stabilizes, beeping steadily now.',
  '',
  'SAM',
  'We saved him! I am so relieved and proud of what we just accomplished together tonight!',
  '',
  'ELENA',
  'Me too, Sam. This reminds me of how good we used to be, both at work and in love.',
  '',
  'INT. HOSPITAL - HALLWAY - NIGHT',
  '',
  'SAM',
  'You did an amazing job in there tonight, Elena. I am really impressed with you, like always.',
  '',
  'ELENA',
  "Thanks, Sam. I still don't know what to do about us, if I'm being honest with you right now.",
  '',
  'SAM',
  "Maybe we should talk about it later tonight, once we've both calmed down a little bit.",
  '',
  'EXT. HOSPITAL - PARKING GARAGE - NIGHT',
  '',
  'SAM',
  'I still love you, Elena. I just wanted you to know that clearly before you drive away tonight.',
  '',
  'ELENA',
  "I know, Sam. I think I still love you too, but I'm too scared to say it back right now.",
].join('\n');

// ── Pair 2 — active vs passive protagonist ────────────────────────────────
// Same premise (analyst Dana Reyes uncovers fraud at Colton Energy): the
// good half has Dana make every decision and take every risk; the bad half
// has a coworker discover it, decide what to do, report it, and take credit
// while Dana only reacts.

const PAIR2_GOOD = [
  "INT. COLTON ENERGY - DANA'S OFFICE - NIGHT",
  '',
  'DANA REYES cross-references two ledgers alone after hours, the building empty except for the hum of the server room down the hall and the rest of the floor dark past the exit signs. She freezes on a duplicated invoice number, checks it twice, then a third time against the original filing.',
  '',
  'DANA',
  '(to herself)',
  "That's not a coincidence.",
  '',
  'DANA',
  '(to herself)',
  'Three years of somebody signing off on this.',
  '',
  'She photographs the screen with her phone, then closes the file exactly as she found it, resets the desk lamp to the angle it was at before, and logs out through the normal exit path instead of just closing the laptop.',
  '',
  'INT. COLTON ENERGY - PARKING GARAGE - NIGHT',
  '',
  'Dana walks fast to her car, glancing once at the camera mounted above the exit. She takes a different route than usual, doubling back past the loading ramp before circling to her actual space.',
  '',
  "INT. DANA'S APARTMENT - NIGHT",
  '',
  "She spreads printouts across the kitchen table, a timeline pinned together with sticky notes and red string. She dials a number copied from a business card she's kept in a drawer for a year.",
  '',
  'DANA',
  "It's Reyes. I need someone at the SEC tonight, not tomorrow. I have documentation.",
  '',
  'DANA',
  "Send everything to my personal address too. I'll follow up myself in the morning either way.",
  '',
  "She doesn't wait for a callback — she starts photographing every page a second time, for a separate copy, and seals the originals in an envelope addressed to her own attorney.",
  '',
  "INT. COLTON ENERGY - CEO'S OFFICE - DAY",
  '',
  "Dana requests a meeting, uninvited, and sits down before she's asked to. CEO MARCUS VANCE looks up, surprised she came alone.",
  '',
  'DANA',
  "I've seen the Q3 reconciliations. I want to know why they don't match what the board was shown.",
  '',
  'VANCE',
  'Careful, Dana.',
  '',
  'DANA',
  'I already made copies. Three sets, three different places.',
  '',
  'VANCE',
  'This conversation never happened.',
  '',
  'DANA',
  "It's already recorded.",
  '',
  'EXT. COLTON ENERGY - LOADING DOCK - DAY',
  '',
  "Security blocks Dana's badge at the main turnstile, apologetic, following a script. She doesn't argue with them — she walks around to the loading dock entrance instead and badges in there, the way she scouted the week before.",
  '',
  'INT. FEDERAL BUILDING - CONFERENCE ROOM - DAY',
  '',
  'Dana slides the folder across the table to two SEC investigators, opening it herself to the tab she wants them to read first.',
  '',
  'DANA',
  "Everything's dated, everything's sourced. I'll testify to all of it, on the record.",
  '',
  'INVESTIGATOR',
  'This is more than we usually get walking in the door.',
  '',
  'DANA',
  'I made sure of that.',
  '',
  'EXT. COURTHOUSE STEPS - DAY',
  '',
  "Cameras flash. Dana walks down the steps alone, past Vance's lawyers, unbothered, checking her watch like she has somewhere else to be.",
].join('\n');

const PAIR2_BAD = [
  "INT. COLTON ENERGY - DANA'S OFFICE - NIGHT",
  '',
  'Dana Reyes is working late, filing reports, when her coworker RAJ bursts in, holding a stack of printouts, breathless, the rest of the floor dark behind him.',
  '',
  'RAJ',
  'You need to see this right now. I found something huge in the ledgers.',
  '',
  'DANA',
  'Oh. Okay. What is it?',
  '',
  'RAJ',
  'Duplicate invoices, going back months. I already know exactly what we should do about it.',
  '',
  'DANA',
  'Whatever you think is best, Raj.',
  '',
  'RAJ',
  "Just let me handle the reporting part. You don't need to worry about any of that.",
  '',
  'DANA',
  'Okay. Whatever makes this easiest.',
  '',
  'INT. COLTON ENERGY - PARKING GARAGE - NIGHT',
  '',
  'Raj walks Dana to her car, explaining everything he found in detail while she listens, nodding along without saying much.',
  '',
  'RAJ',
  "I already called my brother-in-law. He's a lawyer, he'll know exactly what to do about all of this.",
  '',
  'DANA',
  "That's good. I wouldn't have known where to even start.",
  '',
  "INT. DANA'S APARTMENT - NIGHT",
  '',
  "Dana's phone rings while she eats dinner alone. It's Raj again, telling her he already reported everything to the board on her behalf.",
  '',
  'RAJ (V.O.)',
  "Don't worry about anything, Dana. I've got it completely handled from here.",
  '',
  'DANA',
  'Okay. Thanks, Raj. I appreciate you taking care of it.',
  '',
  'RAJ (V.O.)',
  "I told the board I'd send the full write-up myself. No need for you to send anything separately.",
  '',
  'DANA',
  "Sounds good. I'll just wait to hear how it goes.",
  '',
  "INT. COLTON ENERGY - CEO'S OFFICE - DAY",
  '',
  'Dana is called into Vance\'s office. He already knows everything before she even sits down.',
  '',
  'VANCE',
  'Raj told me you two found some irregularities in the ledgers this week.',
  '',
  'DANA',
  'I guess we did, yeah.',
  '',
  'VANCE',
  "You're on leave until this settles down. HR will be in touch with you soon.",
  '',
  'DANA',
  "Okay. If that's what needs to happen.",
  '',
  'EXT. COLTON ENERGY - PARKING GARAGE - DAY',
  '',
  'Dana carries a box of her belongings out to her car in silence. Raj waves at her from across the lot, already talking animatedly to a reporter with a microphone.',
  '',
  "INT. DANA'S APARTMENT - DAY",
  '',
  'Dana watches the news alone on her couch. Raj is on screen, being interviewed about the fraud he uncovered at Colton Energy.',
  '',
  'REPORTER (ON TV)',
  'Whistleblower Raj Patel says the numbers never added up, not even once.',
  '',
  'Dana turns off the television and sits in the quiet for a moment.',
  '',
  'EXT. COURTHOUSE STEPS - DAY',
  '',
  'Dana stands in the crowd, watching Vance get led out in handcuffs. A stranger bumps into her, not recognizing her at all. She says nothing and walks away.',
].join('\n');

// ── Pair 3 — escalation vs flat repetition ────────────────────────────────
// Same premise (bomb tech Jess Kane, partner Lou): the good half escalates
// with a reversal (decoy timer, hidden second device, protocol broken to
// win); the bad half repeats the identical low-stakes beat four times with
// no rise in difficulty and no reversal.

const PAIR3_GOOD = [
  'INT. OFFICE BUILDING - LOBBY - DAY',
  '',
  'JESS KANE suits up in the heavy vest while her partner LOU clears the last stragglers out the revolving doors, waving them across the street. She checks her kit twice, out of habit more than doubt.',
  '',
  'LOU',
  'Sixty in the bag. Clock says twelve minutes.',
  '',
  'JESS',
  "Then I've got eleven to work with.",
  '',
  'LOU',
  'Anyone still inside?',
  '',
  'JESS',
  "Cleared floor by floor. Go be useful topside.",
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - DAY',
  '',
  'Jess kneels by the device — wires, a simple timer, bolted to the underside of a mail cart. She opens the panel, confident, running her thumb along the casing, weighing it in her palm before she commits to anything.',
  '',
  'JESS',
  'Standard rig. Red first.',
  '',
  'LOU (V.O.)',
  "Copy. I'm topside if you need me.",
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - CONTINUOUS',
  '',
  'She cuts the red wire cleanly. The timer does not stop — it speeds up, numbers blurring.',
  '',
  'JESS',
  "That's new.",
  '',
  'LOU (V.O.)',
  'Jess, talk to me.',
  '',
  'JESS',
  "It's a decoy board. There's a second timer under the first, wired separate.",
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - CONTINUOUS',
  '',
  'Jess pries up the hidden second panel, hands shaking now for the first time. Three minutes left. A wire runs from the board to a battery pack that should not be there at all.',
  '',
  'JESS',
  "It's rigged to the fire suppression line. If it blows, it's not just this floor, it's the whole riser.",
  '',
  'LOU (V.O.)',
  'Get out of there, Jess.',
  '',
  'JESS',
  'Not yet.',
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - CONTINUOUS',
  '',
  'One minute. Jess makes a call she cannot take back — she ignores every wire on the board and cuts the battery lead instead.',
  '',
  'JESS',
  'Forget the wires. Kill the power at the source.',
  '',
  'The timer stutters, flickers, goes dark.',
  '',
  'INT. OFFICE BUILDING - LOBBY - DAY',
  '',
  'Jess walks out into daylight, hands still trembling, vest half-unclipped. Lou meets her at the doors, already reaching to steady her.',
  '',
  'LOU',
  'You did not follow protocol in there.',
  '',
  'JESS',
  'Protocol was wrong about the rig.',
  '',
  'LOU',
  'Remind me to update the manual.',
  '',
  'LOU',
  "Command's going to want a full report on the decoy board.",
  '',
  'JESS',
  "They'll get one. Eventually.",
  '',
  'EXT. OFFICE BUILDING - DAY',
  '',
  'Jess sits on the curb as the bomb squad truck pulls away, peeling off her gloves finger by finger. The street stays quiet except for radio chatter easing off, one channel at a time. She looks back at the building once, then does not again.',
].join('\n');

const PAIR3_BAD = [
  'INT. OFFICE BUILDING - LOBBY - DAY',
  '',
  'JESS KANE suits up in the vest, checking the same buckles in the same order she always does. Her partner LOU clears the lobby, waving people across the street the way they always do.',
  '',
  'LOU',
  "Bomb's upstairs. Ten minutes on the clock.",
  '',
  'JESS',
  'Got it.',
  '',
  'LOU',
  'Same as the drill.',
  '',
  'JESS',
  'Same as the drill.',
  '',
  'LOU',
  'You want backup on this one?',
  '',
  'JESS',
  "It's routine. I've got it.",
  '',
  'LOU',
  "Radio if that changes.",
  '',
  'JESS',
  "It won't.",
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - DAY',
  '',
  'Jess kneels by the device, bolted under a mail cart. She opens the panel calmly.',
  '',
  'JESS',
  'Wires. Standard rig.',
  '',
  'LOU (V.O.)',
  'Copy that.',
  '',
  'JESS',
  'Cutting now.',
  '',
  'She cuts the red wire. The timer stops cleanly. Nothing unusual about it.',
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - CONTINUOUS',
  '',
  'Jess finds a second, identical device down the hall, bolted the same way as the first.',
  '',
  'JESS',
  'Another one. Standard rig.',
  '',
  'JESS',
  'Cutting now.',
  '',
  'She cuts the red wire. The timer stops. Nothing unusual about it.',
  '',
  'LOU (V.O.)',
  'Nice work.',
  '',
  'JESS',
  'Just like the first one.',
  '',
  'INT. OFFICE BUILDING - ELEVATOR BANK - CONTINUOUS',
  '',
  'A third device, same as the first two, bolted under another cart the same way.',
  '',
  'JESS',
  'Standard rig again.',
  '',
  'JESS',
  'Cutting now.',
  '',
  'She cuts the red wire. The timer stops. Nothing unusual about it.',
  '',
  'LOU (V.O.)',
  'Another one down.',
  '',
  'JESS',
  'Yep.',
  '',
  'INT. OFFICE BUILDING - STAIRWELL - DAY',
  '',
  'A fourth device on the landing, identical to the rest, bolted the same way as all three before it.',
  '',
  'JESS',
  'Same as the others.',
  '',
  'LOU (V.O.)',
  'Copy that.',
  '',
  'JESS',
  'Cutting now.',
  '',
  'She cuts the red wire. The timer stops. Nothing unusual about it.',
  '',
  'INT. OFFICE BUILDING - LOBBY - DAY',
  '',
  'Jess walks out, unclipping her vest. Lou meets her at the doors.',
  '',
  'LOU',
  'All clear?',
  '',
  'JESS',
  'All clear. Four for four.',
  '',
  'LOU',
  'Routine day, then.',
  '',
  'JESS',
  'Routine day.',
  '',
  'LOU',
  'No surprises this time.',
  '',
  'JESS',
  'None at all.',
  '',
  'LOU',
  'See you tomorrow, same as ever.',
  '',
  'JESS',
  'Same as ever.',
  '',
  'LOU',
  "I'll write it up the same as the others.",
  '',
  'JESS',
  'Sounds right.',
  '',
  'LOU',
  'Same time tomorrow?',
  '',
  'JESS',
  'Probably.',
  '',
  'EXT. OFFICE BUILDING - DAY',
  '',
  'Jess sits on the curb as the bomb squad truck pulls away, peeling off her gloves finger by finger, same as every other day. The street is quiet, same as always. Nothing about today felt any different from the last one.',
].join('\n');

// ── Pair 4 — setup/payoff vs orphaned setups ──────────────────────────────
// Same premise, same two planted details (a service elevator with a dead
// camera; a guard's hand tremor): the good half fires both — the crew
// escapes through the dead elevator, the tremor stops the guard from
// pulling the trigger. The bad half plants the identical details and then
// routes around them entirely — the crew uses the main hallway, and an
// unrelated second guard resolves the confrontation, orphaning both clues.

const PAIR4_GOOD = [
  'INT. WAREHOUSE - HIDEOUT - NIGHT',
  '',
  'NINA VARGAS pins blueprints to a corkboard, moving pins as she talks, the warehouse lit by a single bare bulb overhead. She circles a service elevator marked OUT OF ORDER - DO NOT USE in red marker.',
  '',
  'NINA',
  "Sub-level two. Camera's been down since March. Nobody fixed it, because nobody's supposed to use that elevator anyway.",
  '',
  'CREW MEMBER',
  'And if maintenance finally shows up?',
  '',
  'NINA',
  "They won't. I checked the work order queue myself.",
  '',
  'CREW MEMBER',
  'How long have you been sitting on that?',
  '',
  'NINA',
  'Since the day I found the vault schematics.',
  '',
  'EXT. MERIDIAN BANK - LOADING DOCK - NIGHT',
  '',
  'Nina watches from across the street as guard DESMOND POOLE takes a smoke break by the dumpsters. His hand shakes lighting the cigarette, twice, before it catches.',
  '',
  'NINA',
  '(to herself)',
  'Tremor. New.',
  '',
  'INT. MERIDIAN BANK - EMPLOYEE ENTRANCE - NIGHT',
  '',
  'Nina, disguised as a records auditor, badge clipped to her blazer, chats up Desmond at the door.',
  '',
  'DESMOND',
  'Sorry. Nerves. New meds since the surgery.',
  '',
  'NINA',
  "Take your time. I've got nowhere to be.",
  '',
  'DESMOND',
  "Most people just walk past me. Appreciate it.",
  '',
  'NINA',
  "Everybody deserves a minute.",
  '',
  'She notes that the tremor gets worse under stress, not better, and files it away without a word.',
  '',
  'INT. MERIDIAN BANK - VAULT CORRIDOR - NIGHT',
  '',
  'The crew moves through in single file. Nina leads them straight to the marked service elevator, ignoring the sign bolted to its doors.',
  '',
  'CREW MEMBER',
  "This one's dead.",
  '',
  'NINA',
  'Dead to the camera log. Not dead to us.',
  '',
  'INT. MERIDIAN BANK - VAULT - NIGHT',
  '',
  'Desmond appears at the vault door, gun raised, his hand shaking badly now, worse than either time before.',
  '',
  'DESMOND',
  "Don't move.",
  '',
  'NINA',
  "Your hand's shaking too hard to pull that trigger clean, Desmond. We both know it.",
  '',
  'He hesitates. Just long enough.',
  '',
  'CREW MEMBER',
  'Move, move.',
  '',
  'NINA',
  "Grab the cash. He won't be quick enough to stop us twice.",
  '',
  'INT. MERIDIAN BANK - VAULT CORRIDOR - NIGHT',
  '',
  'The crew escapes back through the dead elevator, exactly as planned, doors closing on the sound of the alarm starting somewhere far above them.',
  '',
  'CREW MEMBER',
  "Nobody's going to think to check sub-level two.",
  '',
  'NINA',
  "That's the whole point of it.",
  '',
  'CREW MEMBER',
  'You planned this down to his hand shaking.',
  '',
  'NINA',
  "I planned this down to everything.",
  '',
  'EXT. MERIDIAN BANK - ALLEY - NIGHT',
  '',
  'Nina strips off her disguise and folds it into a bag. Behind her, alarms finally reach the street, muffled through three floors of concrete.',
].join('\n');

const PAIR4_BAD = [
  'INT. WAREHOUSE - HIDEOUT - NIGHT',
  '',
  'NINA VARGAS pins blueprints to a corkboard, the warehouse lit by a single bare bulb overhead, boxes stacked against every wall the same as they were last week. She circles a service elevator marked OUT OF ORDER - DO NOT USE in red marker.',
  '',
  'NINA',
  "Sub-level two. Camera's been down since March.",
  '',
  'CREW MEMBER',
  'Good to know.',
  '',
  'NINA',
  'Yeah.',
  '',
  'CREW MEMBER',
  'Anything else on the blueprints?',
  '',
  'NINA',
  'Just the usual stuff.',
  '',
  'CREW MEMBER',
  "We'll go over it again tomorrow, then.",
  '',
  'NINA',
  'Sure.',
  '',
  'CREW MEMBER',
  'Same time as always?',
  '',
  'NINA',
  'Same time as always.',
  '',
  'EXT. MERIDIAN BANK - LOADING DOCK - NIGHT',
  '',
  'Nina watches from across the street as guard DESMOND POOLE takes a smoke break by the dumpsters. His hand shakes lighting the cigarette.',
  '',
  'NINA',
  '(to herself)',
  'Huh.',
  '',
  'INT. MERIDIAN BANK - EMPLOYEE ENTRANCE - NIGHT',
  '',
  'Nina, disguised as a records auditor, chats up Desmond at the door.',
  '',
  'DESMOND',
  'Long night ahead, huh?',
  '',
  'NINA',
  'Something like that.',
  '',
  'DESMOND',
  'Tell me about it.',
  '',
  'DESMOND',
  'You get used to it after a while.',
  '',
  'NINA',
  'I bet.',
  '',
  'DESMOND',
  'Anyway, go on in. Have a good one.',
  '',
  'NINA',
  'You too.',
  '',
  'INT. MERIDIAN BANK - VAULT CORRIDOR - NIGHT',
  '',
  'The crew moves through the main corridor, badges cloned, straight past the marked service elevator without a glance, fluorescent lights buzzing overhead.',
  '',
  'CREW MEMBER',
  "Main hallway's clear.",
  '',
  'NINA',
  'Good. Keep moving.',
  '',
  'CREW MEMBER',
  'This whole floor is quiet.',
  '',
  'NINA',
  "It usually is, this time of night.",
  '',
  'CREW MEMBER',
  'Good. Let\'s keep it that way.',
  '',
  'CREW MEMBER',
  "Same setup as the last job.",
  '',
  'NINA',
  'Pretty much.',
  '',
  'INT. MERIDIAN BANK - VAULT - NIGHT',
  '',
  'Desmond appears at the vault door, gun raised.',
  '',
  'DESMOND',
  "Don't move.",
  '',
  'A second guard tackles him from behind before he can react.',
  '',
  'CREW MEMBER',
  'Got him.',
  '',
  'NINA',
  'Nice.',
  '',
  'CREW MEMBER',
  "Wasn't expecting that.",
  '',
  'NINA',
  'Neither was he.',
  '',
  'NINA',
  'Grab the cash and let\'s go before anyone else shows up.',
  '',
  'INT. MERIDIAN BANK - VAULT CORRIDOR - NIGHT',
  '',
  'The crew escapes through the main stairwell instead, alarms already blaring behind them.',
  '',
  'CREW MEMBER',
  "Stairwell's clear all the way down.",
  '',
  'NINA',
  'Keep moving.',
  '',
  'CREW MEMBER',
  'This is taking longer than I thought it would.',
  '',
  'NINA',
  'Just keep moving.',
  '',
  'EXT. MERIDIAN BANK - ALLEY - NIGHT',
  '',
  'Nina strips off her disguise and folds it into a bag, same as she always does after a job like this. Behind her, alarms finally reach the street, muffled through three floors of concrete.',
].join('\n');

// ── Pair 5 — dramatized vs told exposition ────────────────────────────────
// Same premise (a mayor's embezzlement scheme through a shell nonprofit):
// the good half reveals the conspiracy through confrontation and physical
// evidence; the bad half has every character recite the entire backstory
// aloud, in full sentences, to people who would already know it.

const PAIR5_GOOD = [
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  'Detective SOFIA REYES tosses a folder in front of her partner, DET. TOM ABARA, not sitting down herself.',
  '',
  'REYES',
  'The nonprofit got two million from the city. Read the board list.',
  '',
  'Abara scans it, stops on one name, taps it twice.',
  '',
  'ABARA',
  "That's the mayor's brother-in-law.",
  '',
  'REYES',
  'Keep reading.',
  '',
  'Abara flips the page. His eyebrows go up. He doesn\'t say anything else — he just reaches for his jacket.',
  '',
  'INT. CITY HALL - HALLWAY - DAY',
  '',
  'Reyes corners the mayor\'s aide, GRACE LIN, near an elevator bank, blocking her path without quite touching her.',
  '',
  'REYES',
  'Two million dollars, one address, zero employees. Walk me through that.',
  '',
  'LIN',
  "I sign what's put in front of me.",
  '',
  'REYES',
  "Then somebody's putting a lot in front of you.",
  '',
  'LIN',
  "I have a job to get back to.",
  '',
  "Lin doesn't answer the rest of it. The elevator arrives; she doesn't get on it.",
  '',
  'INT. NONPROFIT OFFICE - DAY',
  '',
  'Reyes and Abara find the office — a single empty room, one desk, no computer, a calendar still turned to March.',
  '',
  'ABARA',
  'This is where two million dollars works?',
  '',
  'REYES',
  'This is where two million dollars disappears.',
  '',
  'She photographs the empty desk from three angles, then checks the calendar again like the date might have changed since she first noticed it.',
  '',
  "EXT. MAYOR'S RESIDENCE - DRIVEWAY - NIGHT",
  '',
  "The mayor's brother-in-law, DEREK VANCE, meets them at his car, keys already in hand, engine already running.",
  '',
  'VANCE',
  "I don't have anything to say to you.",
  '',
  'REYES',
  "Then don't say it. Just tell me where the money went.",
  '',
  'He gets in the car without answering. Reyes photographs his plate as he pulls away.',
  '',
  'INT. PRECINCT - INTERROGATION ROOM - DAY',
  '',
  'Grace Lin, alone now, no lawyer, slides a flash drive across the table.',
  '',
  'LIN',
  "He told me if anyone asked, I was supposed to burn this.",
  '',
  'REYES',
  "Why didn't you?",
  '',
  'LIN',
  'I got tired of being the one who burns things.',
  '',
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  "Reyes plugs in the drive. Wire transfers, dates, the mayor's initials on every one, scrolling past on the monitor.",
  '',
  'ABARA',
  "That's not a brother-in-law problem anymore.",
  '',
  'REYES',
  "No. It's his.",
  '',
  'EXT. CITY HALL - STEPS - DAY',
  '',
  "Reyes climbs the steps, warrant in hand, past reporters who don't yet know why she's there, past a photo of the mayor still hanging in the lobby window.",
].join('\n');

const PAIR5_BAD = [
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  'Detective SOFIA REYES sits with her partner, DET. TOM ABARA, coffee going cold between them.',
  '',
  'REYES',
  "So here's what happened. Five years ago, the mayor's brother-in-law, Derek Vance, set up a nonprofit as a front for embezzling city funds.",
  '',
  'ABARA',
  "Right, and since then he's funneled about two million dollars through fake grants to different fake programs.",
  '',
  'REYES',
  'Exactly. The mayor knew the whole time because he needed the money for his re-election campaign next year.',
  '',
  'ABARA',
  'Makes sense. That lines up with everything we already knew about him.',
  '',
  'INT. CITY HALL - HALLWAY - DAY',
  '',
  "Reyes talks to the mayor's aide, GRACE LIN, in the hallway.",
  '',
  'LIN',
  "Let me explain everything. The nonprofit doesn't have any real employees. It's just a shell company the mayor's family uses to launder campaign donations.",
  '',
  'REYES',
  "I see. So you've known about this the whole time, this whole scheme?",
  '',
  'LIN',
  "Yes, I've known for three years, but I was too scared to say anything because I was afraid of losing my job over it.",
  '',
  'INT. NONPROFIT OFFICE - DAY',
  '',
  'Reyes and Abara look around the empty office.',
  '',
  'ABARA',
  'Like I said, this proves my theory that the whole nonprofit is fake and was created specifically to hide the embezzled money.',
  '',
  'REYES',
  'Right, just like we suspected all along, exactly like the tip said.',
  '',
  "EXT. MAYOR'S RESIDENCE - DRIVEWAY - NIGHT",
  '',
  'Derek Vance explains himself to Reyes in the driveway.',
  '',
  'VANCE',
  "Fine, I'll tell you everything. Yes, I took the money. The mayor asked me to do it because he needed cash for his campaign, and I felt like I had no choice but to help my own family.",
  '',
  'REYES',
  'That is a serious admission, Mr. Vance. I hope you understand what that means for you legally.',
  '',
  'INT. PRECINCT - INTERROGATION ROOM - DAY',
  '',
  'Grace Lin explains further in the interrogation room.',
  '',
  'LIN',
  "Like I told you, I have proof. It's all on this flash drive, wire transfers, dates, everything you need to prove the mayor is guilty of embezzlement.",
  '',
  'REYES',
  'Thank you for finally telling the truth. This will help our case enormously.',
  '',
  'INT. PRECINCT - BULLPEN - DAY',
  '',
  'Reyes explains the plan to Abara back at the bullpen.',
  '',
  'REYES',
  'Now that we have the evidence, we can finally arrest the mayor for embezzlement and put an end to this whole scheme once and for all.',
  '',
  'ABARA',
  'Good. I always knew something was off about him, ever since he got elected.',
  '',
  'EXT. CITY HALL - STEPS - DAY',
  '',
  'Reyes walks up the steps to arrest the mayor, cameras already gathering.',
  '',
  'REYES',
  'Finally, justice will be served, after all this time.',
].join('\n');

// ── Pair 6 — composite reviewer scenario ──────────────────────────────────
// The reviewer's original finding, reconstructed at matched size: one
// script combining all five virtues above (subtext, active protagonist,
// escalation with reversal, a paid-off setup, dramatized backstory, and an
// ironic/withheld ending), one combining all five failures (on-the-nose,
// passive, flat/repetitive relief beats, an orphaned setup, told backstory,
// and an ending resolved by someone else with no irony).

const PAIR6_GOOD = [
  'EXT. MORROW COUNTY - ROADSIDE - DAWN',
  '',
  'SHERIFF ADDIE MORROW crouches over a bicycle in the ditch, one pedal bent backward, dew still on the frame. She turns a friendship bracelet out of the spokes without a word, holds it a moment, pockets it, and photographs the tire tracks before anyone else arrives.',
  '',
  "INT. SHERIFF'S OFFICE - DAY",
  '',
  "A deputy sits across the desk. Addie doesn't look up from the map she's marking, a red circle already drying on the quarry road.",
  '',
  'DEPUTY',
  'Same road your sister disappeared on.',
  '',
  'ADDIE',
  'I know which road it is.',
  '',
  'DEPUTY',
  'Just saying it out loud.',
  '',
  'ADDIE',
  "Don't.",
  '',
  'She circles a second point on the map before he can say anything else.',
  '',
  'INT. MORROW HOUSE - KITCHEN - NIGHT',
  '',
  "Addie's mother sets down a mug Addie doesn't touch, wipes her hands on her apron though they're already dry.",
  '',
  'MOTHER',
  "You don't have to be the one who finds her.",
  '',
  'ADDIE',
  'Somebody has to be.',
  '',
  'MOTHER',
  "It doesn't have to be you every time.",
  '',
  'ADDIE',
  'It does this time.',
  '',
  'MOTHER',
  'You always say that.',
  '',
  'Addie is already reaching for her jacket, keys in hand before her mother finishes the sentence.',
  '',
  'EXT. QUARRY ROAD - NIGHT',
  '',
  "Addie follows tire tracks alone, against dispatch's advice crackling on the radio, until they end at a locked gate chained twice over. She cuts the padlock herself with bolt cutters from her trunk.",
  '',
  'INT. QUARRY - STORAGE SHED - CONTINUOUS',
  '',
  'Addie finds the missing girl, alive, tied but breathing, blinking against the flashlight. On the floor beside her: a second bracelet, matching the first exactly.',
  '',
  'ADDIE',
  '(quiet)',
  'You kept it the same as she did.',
  '',
  "The girl doesn't understand what she means. Addie doesn't explain — she just cuts the rope, checks her pulse, and gets her moving toward the light.",
  '',
  'EXT. QUARRY - NIGHT',
  '',
  "Addie carries the girl out past the man who took her, already in cuffs, already talking, explaining himself to the deputies. Addie doesn't slow down to listen to any of it.",
  '',
  "INT. SHERIFF'S OFFICE - DAY (LATER)",
  '',
  'Addie logs the bracelet into evidence, then holds it a second too long before she does, turning it once in her fingers.',
  '',
  'DEPUTY',
  "You gonna tell her mother whose bracelet that really is?",
  '',
  'ADDIE',
  'Let her have this one first.',
  '',
  'She closes the case file on both girls at once, the old one and the new one, and puts them in the same drawer.',
].join('\n');

const PAIR6_BAD = [
  'EXT. MORROW COUNTY - ROADSIDE - DAWN',
  '',
  'SHERIFF ADDIE MORROW stands over a bicycle in the ditch. A friendship bracelet lies tangled in the spokes. Deputy JIM walks up behind her, chewing gum loudly, sipping a gas station coffee.',
  '',
  'JIM',
  "Huh, weird, a bracelet. Anyway, Sheriff, this is really bringing back memories of your sister who disappeared on this same road ten years ago, isn't it?",
  '',
  'ADDIE',
  'Yes, Jim, it really is. I still feel so guilty about not finding her, all these years later.',
  '',
  "INT. SHERIFF'S OFFICE - DAY",
  '',
  'JIM',
  "I already called in the state troopers. They're taking over the search from here, Sheriff, so you don't have to worry.",
  '',
  'ADDIE',
  'Oh. Okay. I guess that makes sense, since they have more resources than we do.',
  '',
  'JIM',
  'They said they\'d call the second they know anything at all.',
  '',
  'ADDIE',
  "That's fine, I guess.",
  '',
  'INT. MORROW HOUSE - KITCHEN - NIGHT',
  '',
  'MOTHER',
  'The troopers called. They said they found some tire tracks out by the quarry, out past the old mill.',
  '',
  'ADDIE',
  "That's good news. I'm glad someone's on it, finally, after all this time.",
  '',
  'EXT. QUARRY ROAD - NIGHT',
  '',
  'Addie waits in her car while the state troopers search the area with flashlights, doing nothing but watching from a distance.',
  '',
  'TROOPER',
  "Sheriff, you should probably just wait here. We've got this handled, no need for you to get involved.",
  '',
  'ADDIE',
  "Okay. If you say so. You know best, I'm sure.",
  '',
  'INT. QUARRY - STORAGE SHED - CONTINUOUS',
  '',
  "The troopers find the missing girl, alive, and radio it in immediately. Addie arrives after, once it's already over, standing in the doorway.",
  '',
  'TROOPER',
  "We got her, Sheriff. She's safe now, no thanks needed.",
  '',
  'ADDIE',
  "Thank goodness. I'm so relieved, I don't know what I would have done otherwise.",
  '',
  'EXT. QUARRY - NIGHT',
  '',
  'The troopers walk the suspect out in cuffs. He explains everything loudly to whoever will listen, practically shouting it.',
  '',
  'SUSPECT',
  'I only did it because I was desperate for money, and I panicked when she saw my face clearly.',
  '',
  'ADDIE',
  "That's terrible. I can't believe someone would do something like that to a child.",
  '',
  "INT. SHERIFF'S OFFICE - DAY (LATER)",
  '',
  'JIM',
  'Great news, Sheriff. Case closed. The troopers are getting a lot of credit for this one in the papers.',
  '',
  'ADDIE',
  "That's fine. I'm just glad it worked out in the end, however it happened.",
  '',
  'She files the paperwork the troopers hand her without reading it closely.',
].join('\n');

export const DISCRIMINATION_PAIRS: DiscriminationPair[] = [
  {
    id: 'subtext-vs-on-the-nose',
    axis: 'subtext-vs-on-the-nose',
    description: 'Elliptical professional dialogue carrying an ex-relationship (good) vs both characters narrating their feelings and the stakes aloud (bad).',
    good: { label: 'Table Four (subtext)', fountain: PAIR1_GOOD },
    bad: { label: 'Table Four (on-the-nose)', fountain: PAIR1_BAD },
  },
  {
    id: 'active-vs-passive-protagonist',
    axis: 'active-vs-passive-protagonist',
    description: 'Protagonist drives every decision and risk (good) vs a coworker discovers, decides, and takes credit while the protagonist only reacts (bad).',
    good: { label: 'The Reconciliation (active)', fountain: PAIR2_GOOD },
    bad: { label: 'The Reconciliation (passive)', fountain: PAIR2_BAD },
  },
  {
    id: 'escalation-vs-flat-repetition',
    axis: 'escalation-vs-flat-repetition',
    description: 'Rising stakes with a genuine reversal (decoy timer, hidden second device, protocol broken to win) (good) vs the identical low-stakes beat repeated four times (bad).',
    good: { label: 'Four Devices (escalation)', fountain: PAIR3_GOOD },
    bad: { label: 'Four Devices (flat)', fountain: PAIR3_BAD },
  },
  {
    id: 'setup-payoff-vs-orphaned-setups',
    axis: 'setup-payoff-vs-orphaned-setups',
    description: "Two planted details (dead elevator camera, a guard's tremor) both fire at the climax (good) vs the identical details planted and then routed around, unresolved (bad).",
    good: { label: 'The Dead Elevator (paid off)', fountain: PAIR4_GOOD },
    bad: { label: 'The Dead Elevator (orphaned)', fountain: PAIR4_BAD },
  },
  {
    id: 'dramatized-vs-told-exposition',
    axis: 'dramatized-vs-told-exposition',
    description: 'The conspiracy is revealed through confrontation and physical evidence (good) vs every character reciting the entire backstory to people who already know it (bad).',
    good: { label: 'The Shell (dramatized)', fountain: PAIR5_GOOD },
    bad: { label: 'The Shell (told)', fountain: PAIR5_BAD },
  },
  {
    id: 'composite-reviewer-scenario',
    axis: 'composite-reviewer-scenario',
    description: "The reviewer's original finding reconstructed: subtext + active protagonist + escalation + a paid-off setup + dramatized backstory + a withheld/ironic ending (good) vs on-the-nose + passive protagonist + flat repetition + an orphaned setup + told backstory + an ending resolved by someone else (bad).",
    good: { label: 'The Morrow Girl (composite strong)', fountain: PAIR6_GOOD },
    bad: { label: 'The Morrow Girl (composite weak)', fountain: PAIR6_BAD },
  },
];
