// Rulebook size — the "how many rule concepts back this verdict" figure
// reported on ScriptDoctorReport.provenance.rulebookCount (server/nvm/
// analyze/types.ts, populated in doctor.ts's aggregation).
//
// Read from docs/rulebook/coverage.json's `totalRuleRecords` — the
// machine-counted authority per docs/rulebook/README.md, generated by
// `npm run rulebook`, never hand-typed — ONCE at module load, mirroring
// server/lib/build-info.ts's readPackageVersion() pattern. doctor.ts's
// aggregation runs on EVERY report, including inside doctor-worker.ts's
// worker thread; a per-run filesystem read would be paid on every single
// analysis instead of once per process/worker. The try/catch fallback (the
// last locked-in count) means a missing or unreadable coverage.json degrades
// to a stale-but-present number rather than crashing analysis — the same
// posture build-info.ts takes on a missing package.json, and the same
// posture every other diagnostic-only ScriptDoctorReport field takes on a
// failed computation (see types.ts's provenance doc comment).
//
// Deliberately its own leaf module with NO import from analyze/** or
// revision/**: doctor.ts and server/nvm/analyze/calibration/reference.ts
// have a live circular import (CLAUDE.md's doctor.ts gotcha — a module-level
// const in doctor.ts itself can be read through a temporal-dead-zone hole by
// reference.ts before doctor.ts finishes evaluating). This file cannot be
// pulled into that cycle no matter what imports it, so doctor.ts importing
// `rulebookCount` from here carries none of that hazard — same reasoning
// doctor.ts's own header already documents for its screenplay-layout.ts
// import.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

/** The count recorded in docs/rulebook/coverage.json as of this file's last
 *  edit — used only if the JSON can't be read at module load (missing file,
 *  malformed JSON, unexpected shape). Update this alongside a deliberate
 *  rulebook regeneration if you notice it drift; a mismatch degrades to a
 *  slightly stale number, never a crash, so it is not load-bearing. */
const FALLBACK_RULEBOOK_COUNT = 3217;

function readRulebookCount(): number {
  try {
    const here = path.dirname(fileURLToPath(import.meta.url));
    const coveragePath = path.join(here, '..', '..', 'docs', 'rulebook', 'coverage.json');
    const raw = JSON.parse(readFileSync(coveragePath, 'utf8')) as { totalRuleRecords?: unknown };
    return typeof raw.totalRuleRecords === 'number' && Number.isFinite(raw.totalRuleRecords)
      ? raw.totalRuleRecords
      : FALLBACK_RULEBOOK_COUNT;
  } catch {
    return FALLBACK_RULEBOOK_COUNT;
  }
}

export const rulebookCount: number = readRulebookCount();
